"""Fast entity tagger against memory-vault/INDEX.md.

INDEX.md is regenerated by ``ciao vault-index`` on server startup and
stores one bullet per vault note, with optional aliases. We parse it
once (mtime-memoized) and then scan incoming prompts for whole-word
mentions of a known name or alias.

Kept deliberately simple: no semantic search, no fuzzy matching. If a
name isn't in INDEX.md verbatim, it won't match. False positives are
cheap; false negatives are fine because Claude can still infer context
from the prompt.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

logger = logging.getLogger(__name__)

# Cap scan cost: we truncate prompts before matching and cap the number
# of entities returned so the injected context stays tiny.
_MAX_PROMPT_CHARS = 4000
_MAX_MATCHES = 8
# Aliases shorter than this produce too many false matches ("mo", "al").
_MIN_ALIAS_LEN = 3

# Bullet lines look like:
#   - `People/Alba` (tags: person, friend; aliases: Alba)
#   - `Projects/Ciaobot-Improvements` (tags: ...)
_BULLET_RE = re.compile(r"^- `(?P<path>[^`]+)`(?P<rest>.*)$")
_ALIASES_RE = re.compile(r"aliases:\s*([^)]+)")
_CATEGORY_PARTS = {
    "People": "People",
    "people": "People",
    "Projects": "Projects",
    "projects": "Projects",
    "Places": "Places",
    "places": "Places",
    "Ideas": "Ideas",
    "ideas": "Ideas",
    "Resources": "Resources",
    "resources": "Resources",
    "Documents": "Documents",
    "documents": "Documents",
    "Workspace": "Workspace",
    "workspace": "Workspace",
}


@dataclass(frozen=True, slots=True)
class VaultEntity:
    """One vault entity surfaceable to the model."""

    name: str
    category: str  # "People", "Projects", "Places", etc.
    path: str  # relative to memory-vault/
    aliases: tuple[str, ...]


class _Index:
    """Parsed INDEX.md held in memory with mtime-based invalidation."""

    __slots__ = ("_path", "_mtime", "_entities", "_match_terms")

    def __init__(self, path: Path) -> None:
        self._path = path
        self._mtime: float = 0.0
        self._entities: list[VaultEntity] = []
        # One compiled regex per distinct matchable term, keyed by lowercase.
        self._match_terms: list[tuple[re.Pattern[str], VaultEntity]] = []

    def _refresh_if_stale(self) -> None:
        try:
            stat = self._path.stat()
        except FileNotFoundError:
            self._entities = []
            self._match_terms = []
            return
        if stat.st_mtime == self._mtime:
            return
        self._mtime = stat.st_mtime
        self._entities = list(_parse_index(self._path))
        self._match_terms = list(_compile_terms(self._entities))
        logger.debug(
            "vault entity index refreshed: %d entities, %d match terms",
            len(self._entities), len(self._match_terms),
        )

    def find(self, prompt: str, *, workspace: str | None = None) -> list[VaultEntity]:
        """Return entities whose name/alias appears as a whole word in ``prompt``."""
        self._refresh_if_stale()
        if not self._match_terms or not prompt:
            return []
        snippet = prompt[:_MAX_PROMPT_CHARS]
        seen: set[str] = set()
        hits: list[VaultEntity] = []
        for pattern, entity in self._match_terms:
            if entity.path in seen:
                continue
            if not _entity_visible_in_workspace(entity, workspace):
                continue
            if pattern.search(snippet):
                hits.append(entity)
                seen.add(entity.path)
                if len(hits) >= _MAX_MATCHES:
                    break
        return hits


def _parse_index(path: Path) -> list[VaultEntity]:
    entities: list[VaultEntity] = []
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return entities
    for line in raw.splitlines():
        match = _BULLET_RE.match(line.strip())
        if not match:
            continue
        rel_path = match.group("path")
        rest = match.group("rest") or ""
        parts = rel_path.split("/")
        if len(parts) < 2:
            continue
        category = _category_for_path(parts)
        name = parts[-1]
        aliases: list[str] = []
        alias_match = _ALIASES_RE.search(rest)
        if alias_match:
            for alias in alias_match.group(1).split(","):
                alias = alias.strip()
                if alias:
                    aliases.append(alias)
        entities.append(VaultEntity(
            name=name,
            category=category,
            path=rel_path,
            aliases=tuple(aliases),
        ))
    return entities


def _category_for_path(parts: list[str]) -> str:
    for part in parts:
        category = _CATEGORY_PARTS.get(part)
        if category:
            return category
    return parts[0]


def _compile_terms(entities: list[VaultEntity]) -> list[tuple[re.Pattern[str], VaultEntity]]:
    """Compile one regex per surface form we want to match against prompts."""
    terms: list[tuple[re.Pattern[str], VaultEntity]] = []
    for entity in entities:
        candidates = {entity.name, *entity.aliases}
        # Also match the display form (spaces instead of dashes) for people/project names.
        candidates.add(entity.name.replace("-", " "))
        for term in candidates:
            term = term.strip()
            if len(term) < _MIN_ALIAS_LEN:
                continue
            pattern = re.compile(
                rf"(?<!\w){re.escape(term)}(?!\w)",
                re.IGNORECASE,
            )
            terms.append((pattern, entity))
    return terms


def _entity_visible_in_workspace(entity: VaultEntity, workspace: str | None) -> bool:
    """Return whether an indexed entity is visible to ``workspace``.

    Workspace-scoped vaults index paths as ``<workspace>/...``. Shared roots
    use ``shared/...`` and are visible everywhere. Older single-workspace
    indexes used unprefixed paths like ``People/Alba``; keep those visible
    only when no workspace filter is requested or for the legacy personal
    workspace.
    """
    workspace = (workspace or "").strip()
    if not workspace:
        return True
    if entity.path.startswith("shared/"):
        return True
    if entity.path.startswith(f"{workspace}/"):
        return True
    if "/" in entity.path:
        first = entity.path.split("/", 1)[0]
        if first in {"People", "Projects", "Places", "Ideas", "Resources"}:
            return workspace == "personal"
    return False


_index_cache: _Index | None = None


def get_index(vault_root: Path) -> _Index:
    """Return the process-wide entity index for a given vault root."""
    global _index_cache
    index_path = vault_root / "INDEX.md"
    if _index_cache is None or _index_cache._path != index_path:
        _index_cache = _Index(index_path)
    return _index_cache


def find_entities(
    prompt: str,
    vault_root: Path,
    *,
    workspace: str | None = None,
) -> list[VaultEntity]:
    """Scan ``prompt`` and return whole-word matches against INDEX.md."""
    return get_index(vault_root).find(prompt, workspace=workspace)


def format_entities(entities: list[VaultEntity]) -> str:
    """Render matched entities as one compact additionalContext block."""
    if not entities:
        return ""
    lines: list[str] = []
    for entity in entities:
        lines.append(f"- [[{entity.path}]] ({entity.category.rstrip('s').lower()})")
    return "mentioned_entities:\n" + "\n".join(lines)
