"""Fast entity tagger against memory-vault/INDEX.md.

INDEX.md is regenerated by ``ciao vault-index`` on server startup and
stores one bullet per vault note, with optional aliases. We parse it
once (mtime-memoized) and then scan incoming prompts for whole-word
mentions of a known name or alias.

Kept deliberately simple: no semantic search, no fuzzy matching. If a
name isn't in INDEX.md verbatim, it won't match. False positives are
cheap; false negatives are fine because Claude can still infer context
from the prompt.
"""

from __future__ import annotations

import logging
import re
from dataclasses import dataclass
from pathlib import Path

from ciao.entity_types import EntityTypeRegistry, load_entity_types
from ciao.vault_index import markdown_destination

logger = logging.getLogger(__name__)

# Cap scan cost: we truncate prompts before matching and cap the number
# of entities returned so the injected context stays tiny.
_MAX_PROMPT_CHARS = 4000
_MAX_MATCHES = 8
# Aliases shorter than this produce too many false matches ("mo", "al").
_MIN_ALIAS_LEN = 3
# README/index represent their whole folder, so we name the entity after the
# parent folder instead of the bare filename (otherwise one "README" token
# lights up every project at once). log/index are structural files whose bare
# names are also common words ("log"), so we drop them from the index entirely;
# the folder's README already stands in for the folder.
_FOLDER_FILENAMES = {"readme"}
_SKIP_FILENAMES = {"log", "index"}

# Bullet lines look like:
#   - [People/Alba](./People/Alba.md) (tags: person, friend; aliases: Alba)
#   - [Projects/Ciaobot-Improvements](./Projects/Ciaobot-Improvements.md) (tags: ...)
# The label carries the vault-relative path, which is what disambiguates two
# notes with the same stem; the destination is the same path made navigable.
# Read the label, not the destination: it needs no unescaping and no `<...>`
# unwrapping (see `vault_index.markdown_destination`).
_BULLET_RE = re.compile(r"^- \[(?P<path>[^\]\n]+)\]\([^)\n]*\)(?P<rest>.*)$")
_ALIASES_RE = re.compile(r"aliases:\s*([^)]+)")
# The default, and the same view `entity_types.EntityTypeRegistry.category_parts`
# returns: this module maps `INDEX.md` bullets, whose folder set is fixed by what
# the indexer wrote, so the folders are a wire format rather than a list of the
# vault's categories. That is why a category the owner adds does NOT join the
# tagger when a registry is passed — see `_category_for_path`. The constant stays
# because it is what a caller with no vault in hand resolves against, and the
# registry is what a caller with one resolves against; with no vault file the two
# are the same fourteen entries.
_CATEGORY_PARTS = {
    "People": "People",
    "people": "People",
    "Projects": "Projects",
    "projects": "Projects",
    "Places": "Places",
    "places": "Places",
    "Ideas": "Ideas",
    "ideas": "Ideas",
    "Resources": "Resources",
    "resources": "Resources",
    "Documents": "Documents",
    "documents": "Documents",
    "Workspace": "Workspace",
    "workspace": "Workspace",
}


@dataclass(frozen=True, slots=True)
class VaultEntity:
    """One vault entity surfaceable to the model."""

    name: str
    category: str  # "People", "Projects", "Places", etc.
    path: str  # relative to memory-vault/
    aliases: tuple[str, ...]


class _Index:
    """Parsed INDEX.md held in memory with mtime-based invalidation."""

    __slots__ = ("_path", "_mtime", "_entities", "_match_terms", "_category_parts")

    def __init__(self, path: Path, registry: EntityTypeRegistry | None = None) -> None:
        self._path = path
        self._mtime: float = 0.0
        self._entities: list[VaultEntity] = []
        # One compiled regex per distinct matchable term, keyed by lowercase.
        self._match_terms: list[tuple[re.Pattern[str], VaultEntity]] = []
        # The folder->category view, resolved once with the index because both
        # are derived from the same vault: a second INDEX.md re-parse must not
        # silently resolve a bullet against a different list than the first.
        self._category_parts: dict[str, str] = (
            _CATEGORY_PARTS if registry is None else registry.category_parts()
        )

    def _refresh_if_stale(self) -> None:
        try:
            stat = self._path.stat()
        except FileNotFoundError:
            self._entities = []
            self._match_terms = []
            return
        if stat.st_mtime == self._mtime:
            return
        self._mtime = stat.st_mtime
        self._entities = list(_parse_index(self._path, self._category_parts))
        self._match_terms = list(_compile_terms(self._entities))
        logger.debug(
            "vault entity index refreshed: %d entities, %d match terms",
            len(self._entities), len(self._match_terms),
        )

    def find(
        self,
        prompt: str,
        *,
        workspace: str | None = None,
        legacy_workspace: str = "",
        index_owns_workspace: bool = False,
    ) -> list[VaultEntity]:
        """Return entities whose name/alias appears as a whole word in ``prompt``."""
        self._refresh_if_stale()
        if not self._match_terms or not prompt:
            return []
        snippet = prompt[:_MAX_PROMPT_CHARS]
        seen: set[str] = set()
        hits: list[VaultEntity] = []
        for pattern, entity in self._match_terms:
            if entity.path in seen:
                continue
            if not _entity_visible_in_workspace(
                entity,
                workspace,
                legacy_workspace=legacy_workspace,
                index_owns_workspace=index_owns_workspace,
            ):
                continue
            if pattern.search(snippet):
                hits.append(entity)
                seen.add(entity.path)
                if len(hits) >= _MAX_MATCHES:
                    break
        return hits


def _parse_index(path: Path, category_parts: dict[str, str] | None = None) -> list[VaultEntity]:
    """Every entity one INDEX.md names, in the order it lists them.

    *category_parts* is the folder -> category view, from
    :meth:`ciao.entity_types.EntityTypeRegistry.category_parts` where a caller
    had a registry to pass and the module constant otherwise. It is a parameter
    rather than a second registry lookup because a parse is a pure read of one
    file: the caller that resolved the view is the one that knows which vault it
    came from.
    """
    parts_map = _CATEGORY_PARTS if category_parts is None else category_parts
    entities: list[VaultEntity] = []
    try:
        raw = path.read_text(encoding="utf-8")
    except OSError:
        return entities
    for line in raw.splitlines():
        match = _BULLET_RE.match(line.strip())
        if not match:
            continue
        rel_path = match.group("path")
        rest = match.group("rest") or ""
        parts = rel_path.split("/")
        if len(parts) < 2:
            continue
        category = _category_for_path(parts, parts_map)
        name = parts[-1]
        lname = name.lower()
        if lname in _SKIP_FILENAMES:
            continue
        # Fold a folder's README onto its folder so the match term is the
        # project name, not a word ("README") shared by every folder.
        if lname in _FOLDER_FILENAMES and len(parts) >= 3:
            name = parts[-2]
        aliases: list[str] = []
        alias_match = _ALIASES_RE.search(rest)
        if alias_match:
            for alias in alias_match.group(1).split(","):
                alias = alias.strip()
                if alias:
                    aliases.append(alias)
        entities.append(VaultEntity(
            name=name,
            category=category,
            path=rel_path,
            aliases=tuple(aliases),
        ))
    return entities


def _category_for_path(parts: list[str], category_parts: dict[str, str]) -> str:
    """The category the path's first known folder names, else its first segment.

    A bullet's label is the vault-relative path the indexer wrote, and the folder
    it starts with is the category — `People/Alba` is a person, and a path whose
    first segment is a workspace name falls back to that name.

    *category_parts* is the view, and it is deliberately NOT widened to the
    vault's own categories. This maps a fixed wire format: the indexer writes
    these folder names and nothing else, so a custom category's folder never
    appears in an INDEX.md bullet and joining the set would only make a
    differently-spelled path resolve differently for no gain. That is the
    documented decision behind `entity_types._CATEGORY_PART_FOLDERS`; a category
    joins this set when the indexer can write it, not before.
    """
    for part in parts:
        category = category_parts.get(part)
        if category:
            return category
    return parts[0]


def _compile_terms(entities: list[VaultEntity]) -> list[tuple[re.Pattern[str], VaultEntity]]:
    """Compile one regex per surface form we want to match against prompts."""
    terms: list[tuple[re.Pattern[str], VaultEntity]] = []
    for entity in entities:
        candidates = {entity.name, *entity.aliases}
        # Also match the display form (spaces instead of dashes) for people/project names.
        candidates.add(entity.name.replace("-", " "))
        for term in candidates:
            term = term.strip()
            if len(term) < _MIN_ALIAS_LEN:
                continue
            pattern = re.compile(
                rf"(?<!\w){re.escape(term)}(?!\w)",
                re.IGNORECASE,
            )
            terms.append((pattern, entity))
    return terms


def _entity_visible_in_workspace(
    entity: VaultEntity,
    workspace: str | None,
    *,
    legacy_workspace: str = "",
    index_owns_workspace: bool = False,
) -> bool:
    """Return whether an indexed entity is visible to ``workspace``.

    Workspace-scoped vaults index paths as ``<workspace>/...``. Older
    single-workspace indexes used unprefixed paths like ``People/Alba``; those
    belong to ``legacy_workspace``, which the caller reads off the workspace
    registry.

    ``index_owns_workspace`` says the index being read covers exactly this one
    workspace, which is true of every per-root ``INDEX.md`` after the
    re-rooting. Then every entry belongs here by construction and there is
    nothing to filter — the prefix rules below describe a shared index and
    become actively wrong. Applying them anyway is what happened on the migrated
    install: per-root indexes are unprefixed, so `People/...`, `Projects/...`
    and the rest fell to the legacy rule, which only admits the ONE workspace
    that owns unprefixed entries. Measured live: every one of the 423 entities in
    the work root was invisible to work chats, while personal worked purely
    because it happened to be the legacy owner. Silently, because entity
    enrichment is fail-open.

    An unknown ``legacy_workspace`` fails closed. Showing an unprefixed entity
    in every workspace is a cross-workspace disclosure; the provider request
    carries the registry-selected owner explicitly for normal PWA chats.

    There is deliberately no cross-workspace visibility escape hatch. A
    ``shared/`` prefix used to be treated as visible everywhere, but nothing
    could reach such a note: every workspace-scoped tool resolves
    ``<vault>/<workspace>`` as its root and ``_safe_relative`` rejects anything
    outside it, so a promoted note became visible to the index and unreadable by
    ``vault_search`` and ``file_read``. Measured on a real two-workspace vault it
    had no users either — zero notes existed in both trees, and every
    cross-workspace reference came from a note filed in the wrong workspace.
    Workspaces are separate; a person belongs to whichever one you deal with them
    in.
    """
    workspace = (workspace or "").strip()
    if not workspace or index_owns_workspace:
        return True
    if entity.path.startswith(f"{workspace}/"):
        return True
    if "/" in entity.path:
        first = entity.path.split("/", 1)[0]
        if first in {"People", "Projects", "Places", "Ideas", "Resources"}:
            return bool(legacy_workspace) and workspace == legacy_workspace
    return False


# One entry per agent root, not one entry total. A single slot was right when
# every workspace shared one INDEX.md; with an index per root, chats alternating
# between workspaces evicted each other's index and re-parsed it on every prompt.
# Keyed by path and bounded by the number of roots an install has.
_index_cache: dict[Path, _Index] = {}
_INDEX_CACHE_LIMIT = 8


def get_index(vault_root: Path, registry: EntityTypeRegistry | None = None) -> _Index:
    """Return the process-wide entity index for a given vault root.

    The vault's category list is loaded here — the root is the agent vault root
    that owns this ``INDEX.md``, which is where ``entity-types.yaml`` lives — so
    the folder -> category view comes from the registry rather than from a second
    copy of it. Omitted, the view is the shipped one, and with no vault file the
    two are identical (``tests/test_entity_types.py``).

    A cached index keeps the view it was built with. It is keyed by path, and it
    is the same file either way, so honouring a later call's registry would mean
    re-parsing one INDEX.md against two lists and letting two chats see different
    categories for one vault. Since the view is a fixed wire format anyway (see
    :func:`_category_for_path`), nothing observable depends on that here.
    """
    index_path = vault_root / "INDEX.md"
    cached = _index_cache.get(index_path)
    if cached is not None:
        return cached
    if len(_index_cache) >= _INDEX_CACHE_LIMIT:
        _index_cache.clear()
    if registry is None:
        registry = load_entity_types(Path(vault_root).resolve())
    index = _Index(index_path, registry)
    _index_cache[index_path] = index
    return index


def find_entities(
    prompt: str,
    vault_root: Path,
    *,
    workspace: str | None = None,
    legacy_workspace: str = "",
    index_owns_workspace: bool = False,
) -> list[VaultEntity]:
    """Scan ``prompt`` and return whole-word matches against INDEX.md.

    ``legacy_workspace`` is the workspace that owns unprefixed pre-migration
    vault entries — pass ``config.primary_workspace()``.

    ``index_owns_workspace`` marks a per-root index, whose every entry belongs to
    the workspace asking. Both callers resolve the root through the same seam
    that knows which layout the install is in, so neither has to guess.
    """
    return get_index(vault_root).find(
        prompt,
        workspace=workspace,
        legacy_workspace=legacy_workspace,
        index_owns_workspace=index_owns_workspace,
    )


def format_entities(entities: list[VaultEntity]) -> str:
    """Render matched entities as one compact additionalContext block.

    Emits relative markdown links, the vault's only link dialect. Paths are
    vault-root-relative with a `./` prefix because this block goes into a
    *prompt*, not into a note — there is no containing file to be relative to,
    and the vault root is the one anchor the model can rely on.
    """
    if not entities:
        return ""
    lines: list[str] = []
    for entity in entities:
        target = markdown_destination(f"./{entity.path}.md")
        lines.append(
            f"- [{entity.name}]({target}) ({entity.category.rstrip('s').lower()})"
        )
    return "mentioned_entities:\n" + "\n".join(lines)


# The capsule's hint block, as format_entities writes it:
#   mentioned_entities:
#   - [Name](./path.md) (category)
# The destination may be angle-bracketed when the path has spaces.
_CAPSULE_RE = re.compile(r"(?s)\[CIAO_CONTEXT_BEGIN\]\n(.*?)\n\[CIAO_CONTEXT_END\]")
_HINT_LINE_RE = re.compile(r"^- \[(?P<name>[^\]]*)\]\((?:<(?P<angled>[^>]*)>|(?P<bare>[^)\s]*))\) \((?P<category>[^)]*)\)$")


def context_entities(prompt: str) -> list[dict[str, str]]:
    """The entity hints a stored prompt's leading capsule carried.

    The inverse of :func:`format_entities`, read back out of the envelope that
    stays in the stored turn, so the chat can show which notes each message
    was matched to without a second record of them. Paths come back
    vault-root-relative without the ``./`` prefix. Empty when the prompt has
    no capsule or the capsule matched nothing.
    """
    capsule = _CAPSULE_RE.match(prompt or "")
    if not capsule:
        return []
    lines = capsule.group(1).splitlines()
    try:
        start = lines.index("mentioned_entities:") + 1
    except ValueError:
        return []
    found: list[dict[str, str]] = []
    for line in lines[start:]:
        match = _HINT_LINE_RE.match(line.strip())
        if not match:
            break
        dest = match.group("angled") if match.group("angled") is not None else match.group("bare")
        path = dest.replace("%3C", "<").replace("%3E", ">").removeprefix("./")
        found.append({"name": match.group("name"), "path": path, "category": match.group("category")})
    return found
