"""Install and mirror Ciaobot skills, commands, agents, and MCP servers."""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SyncSkillsResult:
    custom_installed: int = 0
    custom_pruned: int = 0
    upstream_updated: int = 0
    upstream_pruned: int = 0
    agents_installed: int = 0
    agents_pruned: int = 0
    commands_installed: int = 0
    commands_pruned: int = 0
    stock_installed: int = 0
    stock_pruned: int = 0
    stock_agents_installed: int = 0
    stock_agents_pruned: int = 0
    legacy_codex_pruned: int = 0
    # opencode needs no skill or instruction projection: it discovers
    # `.claude/skills`, `.agents/skills`, `AGENTS.md`, and `CLAUDE.md` natively.
    opencode_agents_installed: int = 0
    opencode_agents_pruned: int = 0
    opencode_commands_installed: int = 0
    opencode_commands_pruned: int = 0
    opencode_mcps_installed: int = 0
    opencode_mcps_pruned: int = 0
    stock_commands_seeded: int = 0
    stock_commands_refreshed: int = 0
    stock_commands_customised: int = 0
    stock_commands_pruned: int = 0


@dataclass(frozen=True)
class StockCommandSync:
    """Outcome of one `_seed_stock_commands` pass."""

    seeded: int = 0
    refreshed: int = 0
    customised: int = 0
    pruned: int = 0


# Marker dropped into skills copied from ciao.stock so stale copies can be
# pruned when the packaged set changes or a workspace skill overrides them.
STOCK_SKILL_MARKER = ".ciao-stock-skill"
STOCK_AGENT_MARKER_SUFFIX = ".ciao-stock-agent"
STOCK_COMMAND_MARKER_SUFFIX = ".ciao-stock-command"
# sha256 of every revision of each stock command ever shipped. An unmarked
# workspace copy whose digest is listed here is a pristine older revision, so
# it is adopted and refreshed rather than treated as user-authored. When you
# edit a stock command, append the digest of the NEW text here too;
# test_stock_command_revision_registry_is_current enforces that.
SHIPPED_STOCK_COMMAND_DIGESTS: dict[str, frozenset[str]] = {
    "critique.md": frozenset({
        "00297ec3eb4e0ccef147fc7743a8003b3fe0293d2c2203dd1c8616ca233a56f5",
        "315453a65b19d645a23c56de38d3add0b5821e1080059f9b2aac9078986a1ede",
        "56971efa173bba88750a503ce20a7e40eb64f02617091699777a83da50e25a83",
        "6038402836157566e160d42de5663867e1e9da299d1d61b306af7d7558f8ccd7",
        "69383c6953f305eccf13abbe123ede51bff09f3b8632cfbd149199522b3ef779",
        "887906f04ac45fde5666fd68c5dfdfd3f6c0b145c6bdd6cf49b9eab97013cd7f",
    }),
    "interrogation.md": frozenset({
        "17600a45d0fd58b5f79a6f865c57243f4bda134aeb31f2f89078223c2449ef71",
        "d21a3788354ffa84ef7178e5e3ff9dd5b159bda518eb210cb4ba2fe6e2e4faa9",
        "efcc5d781e3d4fb04657ba6505b833c56bb07851bac28d7d34f634a745fe7408",
    }),
    "remember.md": frozenset({
        "5bbbc47cc694ee6499e9189a8f571b4135890df451b48d279b1d8e65d43d790d",
        "7aaca3b9e0c94e8d5cf7c2b0afd802fdc91c3569fba9d2f63bf344e1e17c5096",
        "86f6854b33701e02518cec19160fb0e2b466c31d48819678088af4c27a9560d5",
        "98950dfedb6db9dc0f2c0e8c39c2164369e3f591d4c1928dd4d18e18a6665fd3",
        "98bf1b2cda1b97d9ae7caf43357d002580b038645737b895a42267f08cf4c7ec",
        "e89dbfdda0580280fdced71cabf50fad529c9824fb275104f60969b000ebb012",
    }),
}
CODEX_WRAPPER_MARKER = ".ciao-codex-wrapper"
CODEX_AGENT_MARKER = "# Generated by Ciaobot from a canonical subagent.\n"
CODEX_CONFIG_BEGIN = "# >>> CIAOBOT MANAGED CODEX AGENTS >>>"
CODEX_CONFIG_END = "# <<< CIAOBOT MANAGED CODEX AGENTS <<<"
CODEX_MCP_CONFIG_BEGIN = "# >>> CIAOBOT MANAGED PROJECT MCPS >>>"
CODEX_MCP_CONFIG_END = "# <<< CIAOBOT MANAGED PROJECT MCPS <<<"
_AGENT_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")

# opencode projections. Skills and instructions need none: opencode discovers
# `.claude/skills/<name>/SKILL.md`, `.agents/skills/<name>/SKILL.md`,
# `AGENTS.md`, and `CLAUDE.md` natively (verified against opencode 1.18).
# Only commands, subagents, and MCP servers need generated files.
#
# Markdown carries its marker as an HTML comment under the frontmatter; JSON
# has no comment syntax, so managed MCP server names are tracked in a sidecar
# and only those are ever pruned from `opencode.json`.
OPENCODE_GENERATED_MARKER = (
    "<!-- Generated by Ciaobot. Edit the canonical source, then run ciao sync-skills. -->"
)
OPENCODE_MANAGED_MCPS_FILE = ".ciao-managed-mcps.json"
OPENCODE_MCP_EXCLUDES = frozenset({"ciaobot", "ciaobot-fastmcp"})

# Legacy setup copies of agents removed from the stock ship set. Sync prunes
# these when they still live only under .claude/agents/ (no subagents/ copy).
LEGACY_REMOVED_STOCK_AGENTS = frozenset({
    "comment-analyzer",
    "doc-updater",
    "pr-test-analyzer",
    "silent-failure-hunter",
})


def _remove_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def _is_custom_skill_link(path: Path) -> bool:
    if not path.is_symlink():
        return False
    try:
        target = os.readlink(path)
    except OSError:
        return False
    return f"/skills/{path.name}" in target


def _ensure_symlink(source: Path, link: Path, *, relative_to: Path | None = None) -> bool:
    source = source.resolve()
    if link.exists():
        try:
            if link.resolve() == source:
                return True
        except OSError:
            pass
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        _remove_path(link)

    link.parent.mkdir(parents=True, exist_ok=True)
    target: Path | str = source
    if relative_to is not None:
        target = os.path.relpath(source, relative_to)
    link.symlink_to(target)
    return True


def _iter_entries(path: Path) -> list[Path]:
    if not path.is_dir():
        return []
    return sorted(path.iterdir(), key=lambda entry: entry.name)


def _install_stock_skills(
    workspace: Path,
    *,
    gws_profile: str | None = None,
) -> tuple[int, int]:
    """Copy packaged ``ciao.stock/skills`` into ``.claude/skills``.

    A workspace ``skills/<name>`` always wins over the packaged skill of the
    same name.  Copies carry ``STOCK_SKILL_MARKER`` so they are refreshed on
    every sync and pruned once they disappear from the package (or become
    shadowed by a workspace skill).

    The ``gws-*`` skills are Google-Workspace integrations and are only
    installed when the workspace has a GWS profile to use them against (see
    ``gws_auth.workspace_gws_profile``). A workspace with no profile connected
    gets the generic skills only — shipping GWS wrappers that name a credential
    directory nobody created just produces auth errors and wasted catalog
    surface. ``gws_profile`` carries the resolved account name: ``None`` (the
    default) installs them unconditionally for callers that predate the profile
    check, ``""`` skips them (no account linked), and a non-empty slug installs
    them.
    """
    from importlib import resources

    claude_skills = workspace / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)
    custom_dir = workspace / "skills"

    try:
        stock_skills = resources.files("ciao.stock").joinpath("skills")
        entries = [entry for entry in stock_skills.iterdir() if entry.is_dir()]
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        entries = []

    installed = 0
    live: set[str] = set()
    for entry in sorted(entries, key=lambda item: item.name):
        if not entry.joinpath("SKILL.md").is_file():
            continue
        if (custom_dir / entry.name / "SKILL.md").is_file():
            continue  # workspace skill shadows the packaged one
        # Google-account skills are gated on an actual profile for this
        # workspace. `gws_profile` is deliberately passed through as a resolved
        # value rather than recomputed here, so callers who already know the
        # workspace's effective profile do not read it twice.
        if entry.name.startswith("gws-") and gws_profile == "":
            continue
        target = claude_skills / entry.name
        if target.is_symlink():
            continue  # user-managed link, leave it alone
        with resources.as_file(entry) as source:
            shutil.copytree(source, target, dirs_exist_ok=True)
        (target / STOCK_SKILL_MARKER).touch()
        live.add(entry.name)
        installed += 1

    pruned = 0
    for existing in _iter_entries(claude_skills):
        if existing.name in live or existing.is_symlink() or not existing.is_dir():
            continue
        if not (existing / STOCK_SKILL_MARKER).exists():
            continue
        shutil.rmtree(existing)
        pruned += 1
    return installed, pruned


def _rebuild_custom_skill_links(workspace: Path) -> tuple[int, int]:
    custom_dir = workspace / "skills"
    claude_skills = workspace / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)

    installed = 0
    if custom_dir.is_dir():
        for skill_dir in sorted(custom_dir.iterdir(), key=lambda entry: entry.name):
            if not skill_dir.is_dir():
                continue
            if not (skill_dir / "SKILL.md").is_file() or (skill_dir / "SKILL.md").stat().st_size == 0:
                continue
            target = claude_skills / skill_dir.name
            _ensure_symlink(skill_dir, target, relative_to=claude_skills)
            installed += 1

    pruned = 0
    for target in _iter_entries(claude_skills):
        if not target.is_symlink() or target.exists():
            continue
        try:
            current = os.readlink(target)
        except OSError:
            continue
        if "/skills/" not in current:
            continue
        target.unlink(missing_ok=True)
        pruned += 1
    return installed, pruned


def mirror_shared_skill_sources(workspace: Path, shared_root: Path) -> tuple[int, int]:
    """Link every skill in a shared source directory into one root's catalog.

    ``<install>/skills-src/`` is a mirror source, not a workspace: it has no
    vault, no guide and no sessions of its own. A skill placed there applies in
    every agent root, so each root gets a symlink rather than a copy — one edit,
    N roots, and no divergence to reconcile later.

    A root's own ``skills/<name>`` WINS. A workspace holding a local copy of a
    shared skill has said something by doing that, and replacing it with the
    shared one would discard the statement. Same precedence rule packaged stock
    skills already follow.

    Returns ``(linked, pruned)``. Pruning is limited to broken links that point
    into the shared directory, so a link the user made by hand is left alone —
    the same conservative rule as ``_rebuild_custom_skill_links``.
    """
    root = Path(workspace)
    shared = Path(shared_root)
    claude_skills = root / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)
    own = root / "skills"
    marker = f"/{shared.name}/"

    linked = 0
    live: set[str] = set()
    if shared.is_dir():
        for entry in sorted(shared.iterdir(), key=lambda item: item.name):
            if not entry.is_dir() or entry.name.startswith("."):
                continue
            skill_md = entry / "SKILL.md"
            if not skill_md.is_file() or skill_md.stat().st_size == 0:
                continue
            if (own / entry.name / "SKILL.md").is_file():
                continue  # the root's own copy wins
            live.add(entry.name)
            _ensure_symlink(entry, claude_skills / entry.name, relative_to=claude_skills)
            linked += 1

    pruned = 0
    for target in _iter_entries(claude_skills):
        if target.name in live or not target.is_symlink() or target.exists():
            continue
        try:
            current = os.readlink(target)
        except OSError:
            continue
        if marker not in current:
            continue
        target.unlink(missing_ok=True)
        pruned += 1
    return linked, pruned


def _stock_agent_marker(agent_path: Path) -> Path:
    return agent_path.with_name(agent_path.name + STOCK_AGENT_MARKER_SUFFIX)


def _stock_command_marker(command_path: Path) -> Path:
    return command_path.with_name(command_path.name + STOCK_COMMAND_MARKER_SUFFIX)


def _stock_command_marker_is_safe(command_path: Path) -> bool:
    # A symlinked marker would make the writer truncate whatever it points at
    # (e.g. ../../.env pulled in from a hostile git checkout).
    return not _stock_command_marker(command_path).is_symlink()


def _read_stock_command_marker(command_path: Path) -> str | None:
    marker = _stock_command_marker(command_path)
    if not marker.is_file():
        return None
    return marker.read_text(encoding="utf-8").strip()


def _write_stock_command_marker(command_path: Path, digest: str) -> None:
    marker = _stock_command_marker(command_path)
    if marker.is_symlink():
        # Belt and braces: the seed loop never reaches a symlinked marker.
        print(
            f"WARN: refusing to write symlinked stock-command marker {marker} "
            f"-> {os.readlink(marker)}",
            file=sys.stderr,
        )
        return
    # Atomic replace so a crash mid-write can never leave a truncated digest
    # behind (the digest is the managed copy's integrity check).
    tmp = marker.with_name(marker.name + ".tmp")
    tmp.write_text(digest, encoding="utf-8")
    os.replace(tmp, marker)


def _unmark_stock_command(command_path: Path) -> None:
    _stock_command_marker(command_path).unlink(missing_ok=True)


def _digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _is_managed_stock_agent(agent_path: Path) -> bool:
    return _stock_agent_marker(agent_path).is_file()


def _mark_stock_agent(agent_path: Path) -> None:
    _stock_agent_marker(agent_path).touch()


def _unmark_stock_agent(agent_path: Path) -> None:
    _stock_agent_marker(agent_path).unlink(missing_ok=True)


def _install_stock_agents(workspace: Path) -> tuple[int, int]:
    """Copy packaged ``ciao.stock/agents`` into ``.claude/agents``.

    A workspace ``subagents/<name>.md`` always wins over the packaged agent of
    the same name. Copies carry a sibling ``*.ciao-stock-agent`` marker so they
    are refreshed on every sync and pruned once they disappear from the package
    (or become shadowed by a workspace subagent).
    """
    from importlib import resources

    agents_dir = workspace / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    custom_dir = workspace / "subagents"

    try:
        stock_agents = resources.files("ciao.stock").joinpath("agents")
        stock_files = sorted(
            (entry for entry in stock_agents.iterdir() if entry.name.endswith(".md")),
            key=lambda item: item.name,
        )
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        stock_files = []

    installed = 0
    live: set[str] = set()
    for stock_entry in stock_files:
        name = stock_entry.name
        if (custom_dir / name).is_file():
            continue  # workspace subagent shadows the packaged agent
        target = agents_dir / name
        if target.is_symlink():
            continue  # user-managed link, leave it alone
        with resources.as_file(stock_entry) as stock_path:
            shutil.copy2(stock_path, target)
        _mark_stock_agent(target)
        live.add(name)
        installed += 1

    pruned = 0
    for existing in _iter_entries(agents_dir):
        if not existing.is_file() or existing.name.endswith(STOCK_AGENT_MARKER_SUFFIX):
            continue
        if not existing.name.endswith(".md") or existing.is_symlink():
            continue
        if existing.name in live:
            continue
        if _is_managed_stock_agent(existing):
            _remove_path(existing)
            _unmark_stock_agent(existing)
            pruned += 1
            continue
        if (
            existing.stem in LEGACY_REMOVED_STOCK_AGENTS
            and not (custom_dir / existing.name).is_file()
        ):
            _remove_path(existing)
            pruned += 1

    for marker in agents_dir.glob(f"*{STOCK_AGENT_MARKER_SUFFIX}"):
        agent_path = marker.with_name(marker.name[: -len(STOCK_AGENT_MARKER_SUFFIX)])
        if agent_path.name not in live and not agent_path.exists():
            marker.unlink(missing_ok=True)

    return installed, pruned


def _seed_stock_commands(workspace: Path) -> StockCommandSync:
    """Ensure packaged commands live in canonical ``commands/``.

    Fresh installs seed from ``ciao.stock/commands``. Older workspaces whose
    canonical copy is missing reach the same state through that plain seed
    path, so ``.claude/commands/`` is never consulted: the mirror there is
    rebuilt from ``commands/`` afterwards like any other.

    A seeded copy carries a sibling ``*.ciao-stock-command`` marker whose
    content is the sha256 hex digest of the exact bytes last written. On
    every sync an unmodified marked copy is refreshed from the package, so
    content fixes reach existing installs. A marked copy whose bytes no
    longer match the marker hash was edited by the user: its marker is
    removed and it is never touched again. A pre-existing copy without a
    marker is adopted when it is byte-identical to the packaged text or
    matches a previously shipped revision listed in
    ``SHIPPED_STOCK_COMMAND_DIGESTS`` (an upgrade's pristine older copy);
    anything else is treated as user-authored and left alone. Marked copies
    whose stock source disappeared from the package are pruned when still
    unmodified; their markers are dropped when the file was edited or is a
    user-managed symlink.
    """
    from importlib import resources

    commands_dir = workspace / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)

    try:
        stock_commands = resources.files("ciao.stock").joinpath("commands")
        stock_files = sorted(
            (entry for entry in stock_commands.iterdir() if entry.name.endswith(".md")),
            key=lambda item: item.name,
        )
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        # An unreadable package must not look like "every stock command was
        # removed": that would prune each managed copy on the next sync.
        return StockCommandSync()

    seeded = 0
    refreshed = 0
    customised = 0
    live: set[str] = set()
    for stock_entry in stock_files:
        name = stock_entry.name
        canonical = commands_dir / name
        if canonical.is_symlink():
            continue  # user-managed link, leave it alone
        if not _stock_command_marker_is_safe(canonical):
            marker = _stock_command_marker(canonical)
            print(
                f"WARN: skipping {name}; stock-command marker {marker} is a "
                f"symlink to {os.readlink(marker)}",
                file=sys.stderr,
            )
            continue  # never follow or replace a symlinked marker
        live.add(name)
        with resources.as_file(stock_entry) as stock_path:
            stock_bytes = stock_path.read_bytes()
            if not canonical.exists():
                # Fresh seed, or migrate a legacy stock copy that lived only
                # under .claude/commands/ and was not editable in Settings.
                canonical.write_bytes(stock_bytes)
                _write_stock_command_marker(canonical, _digest(stock_bytes))
                seeded += 1
                continue
            stock_digest = _digest(stock_bytes)
            marker_digest = _read_stock_command_marker(canonical)
            if marker_digest is None:
                # Pre-existing install from before markers: adopt an identical
                # copy, adopt a pristine older shipped revision, treat
                # anything else as user-authored.
                existing_digest = _digest(canonical.read_bytes())
                if existing_digest == stock_digest:
                    _write_stock_command_marker(canonical, stock_digest)
                elif existing_digest in SHIPPED_STOCK_COMMAND_DIGESTS.get(name, frozenset()):
                    # An unmarked copy whose bytes match a previously shipped
                    # revision is a pristine older revision, not a user edit:
                    # refresh it to the packaged text and adopt it.
                    canonical.write_bytes(stock_bytes)
                    _write_stock_command_marker(canonical, stock_digest)
                    refreshed += 1
                else:
                    customised += 1
                continue
            if _digest(canonical.read_bytes()) != marker_digest:
                # The user edited our copy: unmark it and never touch it again.
                _unmark_stock_command(canonical)
                customised += 1
                continue
            if stock_digest != marker_digest:
                # Managed and unmodified: refresh to the packaged revision.
                canonical.write_bytes(stock_bytes)
                _write_stock_command_marker(canonical, stock_digest)
                refreshed += 1

    pruned = 0
    for marker in commands_dir.glob(f"*{STOCK_COMMAND_MARKER_SUFFIX}"):
        command_path = marker.with_name(marker.name[: -len(STOCK_COMMAND_MARKER_SUFFIX)])
        if marker.is_symlink():
            # Never unlink or read a symlinked marker: the link itself is not
            # ours and its target must stay untouched.
            continue
        if command_path.name in live:
            continue
        if command_path.is_file() and not command_path.is_symlink():
            marker_digest = _read_stock_command_marker(command_path)
            if marker_digest is not None and _digest(command_path.read_bytes()) == marker_digest:
                _remove_path(command_path)
                _unmark_stock_command(command_path)
                pruned += 1
                continue
        _unmark_stock_command(command_path)

    return StockCommandSync(
        seeded=seeded,
        refreshed=refreshed,
        customised=customised,
        pruned=pruned,
    )


def _mirror_dir_symlinks(
    source_dir: Path,
    dest_dir: Path,
    *,
    glob_pattern: str = "*",
    prune_regular: bool,
) -> tuple[int, int]:
    dest_dir.mkdir(parents=True, exist_ok=True)
    linked = 0
    live: set[str] = set()
    if source_dir.is_dir():
        for entry in sorted(source_dir.glob(glob_pattern), key=lambda item: item.name):
            if not entry.exists():
                if entry.is_symlink():
                    print(
                        f"WARN: skipping dangling symlink {entry} -> {os.readlink(entry)}",
                        file=sys.stderr,
                    )
                continue
            live.add(entry.name)
            _ensure_symlink(entry, dest_dir / entry.name)
            linked += 1

    pruned = 0
    for entry in _iter_entries(dest_dir):
        if entry.name in live:
            continue
        if not prune_regular and not entry.is_symlink():
            continue
        _remove_path(entry)
        pruned += 1
    return linked, pruned


def _frontmatter_and_body(text: str) -> tuple[dict[str, str], str]:
    from ciao.web.commands import _FRONTMATTER_RE, _parse_frontmatter

    return _parse_frontmatter(text), _FRONTMATTER_RE.sub("", text, count=1).strip()


def _without_managed_codex_config(text: str) -> tuple[str, bool]:
    """Remove Ciaobot's prior agent-registration block from TOML text."""
    start = text.find(CODEX_CONFIG_BEGIN)
    if start < 0:
        return text, False
    end = text.find(CODEX_CONFIG_END, start)
    if end < 0:
        # A partial marker may be user-edited or truncated. Refuse to guess.
        return text, True
    end += len(CODEX_CONFIG_END)
    if end < len(text) and text[end] == "\n":
        end += 1
    return (text[:start].rstrip() + "\n" + text[end:].lstrip()).strip() + "\n", False


def _without_managed_codex_mcp_config(text: str) -> tuple[str, bool]:
    """Remove Ciaobot's prior project-MCP block from TOML text."""
    start = text.find(CODEX_MCP_CONFIG_BEGIN)
    if start < 0:
        return text, False
    end = text.find(CODEX_MCP_CONFIG_END, start)
    if end < 0:
        # A partial marker may be user-edited or truncated. Refuse to guess.
        return text, True
    end += len(CODEX_MCP_CONFIG_END)
    if end < len(text) and text[end] == "\n":
        end += 1
    return (text[:start].rstrip() + "\n" + text[end:].lstrip()).strip() + "\n", False


def _cleanup_legacy_codex_projections(workspace: Path) -> int:
    """Remove only artifacts Ciaobot can prove it generated for Codex.

    Codex is no longer a runtime provider, but upgrades must not delete a
    user's own ``.codex`` configuration or skills. Every removable artifact
    therefore carries one of the old Ciaobot markers; unmarked files are left
    untouched.
    """
    pruned = 0
    wrapper_root = workspace / ".agents" / "skills"
    for entry in _iter_entries(wrapper_root):
        if entry.is_dir() and (entry / CODEX_WRAPPER_MARKER).is_file():
            _remove_path(entry)
            pruned += 1

    agent_root = workspace / ".codex" / "agents"
    for entry in _iter_entries(agent_root):
        if not entry.is_file() or entry.suffix != ".toml":
            continue
        try:
            managed = entry.read_text(encoding="utf-8").startswith(CODEX_AGENT_MARKER)
        except OSError:
            continue
        if managed:
            _remove_path(entry)
            pruned += 1

    config_path = workspace / ".codex" / "config.toml"
    try:
        original = config_path.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        original = ""
    if original:
        without_agents, partial_agents = _without_managed_codex_config(original)
        without_mcps, partial_mcps = _without_managed_codex_mcp_config(without_agents)
        if not partial_agents and not partial_mcps and without_mcps != original:
            config_path.write_text(without_mcps, encoding="utf-8")
            pruned += 1
    return pruned


def _env_var_name(value: object) -> str:
    """The variable name behind a `${NAME}` reference, else "".

    A literal value yields "" so callers drop it rather than copy a credential
    into a tracked config file.
    """
    raw = str(value or "").strip()
    match = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", raw)
    return match.group(1) if match else ""


def _opencode_env_placeholder(value: object) -> str:
    """Return an opencode `{env:NAME}` reference, never a literal credential.

    opencode does not understand `${NAME}`. Its config interpolation is
    `{env:VAR}` (plus `{file:path}`), and anything else is passed through
    verbatim — a projected `${NOTION_TOKEN}` reached the Notion MCP server as
    the literal bearer token and every call came back 401. The remote branch of
    `_opencode_mcp_entry` already emitted the right shape; only local servers,
    which carry credentials in `environment`, were wrong.
    """
    name = _env_var_name(value)
    return f"{{env:{name}}}" if name else ""


def _bearer_env_name(headers: object) -> str:
    if not isinstance(headers, dict):
        return ""
    authorization = str(headers.get("Authorization") or headers.get("authorization") or "")
    match = re.fullmatch(r"Bearer\s+\$\{([A-Za-z_][A-Za-z0-9_]*)\}", authorization.strip())
    return match.group(1) if match else ""


def _opencode_generated(path: Path) -> bool:
    """Whether a generated file is Ciaobot's to rewrite or prune."""
    try:
        return OPENCODE_GENERATED_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def _write_opencode_projection(target: Path, frontmatter: list[str], body: str) -> bool:
    """Write a marked Markdown projection, leaving user-authored files alone."""
    if target.exists() and not _opencode_generated(target):
        return False
    content = (
        "---\n" + "\n".join(frontmatter) + "\n---\n\n"
        + OPENCODE_GENERATED_MARKER + "\n\n"
        + body.strip() + "\n"
    )
    try:
        if target.exists() and target.read_text(encoding="utf-8") == content:
            return True
        target.write_text(content, encoding="utf-8")
    except OSError:
        return False
    return True


def _prune_opencode_dir(target_root: Path, live: set[str]) -> int:
    """Remove generated files no longer backed by a canonical source."""
    pruned = 0
    for entry in _iter_entries(target_root):
        if entry.name in live or not entry.is_file():
            continue
        if not _opencode_generated(entry):
            continue
        _remove_path(entry)
        pruned += 1
    return pruned


def _install_opencode_agents(workspace: Path) -> tuple[int, int]:
    """Compile canonical Ciaobot roles into opencode subagent definitions.

    opencode's agent format is Markdown with YAML frontmatter, so the canonical
    `subagents/<name>.md` files need only a `mode: subagent` line added.
    `tools` and `model` are deliberately omitted: omission inherits the
    parent's, which is safer than translating Claude tool names.
    """
    target_root = workspace / ".opencode" / "agents"
    target_root.mkdir(parents=True, exist_ok=True)
    live: set[str] = set()
    installed = 0
    for source in _canonical_agent_sources(workspace):
        name = source.stem
        if not _AGENT_NAME_RE.fullmatch(name):
            continue
        try:
            frontmatter, body = _frontmatter_and_body(source.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not body.strip():
            continue
        description = frontmatter.get("description", "").strip() or f"Ciaobot {name} role"
        target = target_root / f"{name}.md"
        if _write_opencode_projection(
            target,
            [f"description: {json.dumps(description, ensure_ascii=False)}", "mode: subagent"],
            body,
        ):
            live.add(target.name)
            installed += 1
    return installed, _prune_opencode_dir(target_root, live)


def _install_opencode_commands(workspace: Path) -> tuple[int, int]:
    """Project canonical Ciaobot commands into opencode's command directory.

    opencode uses the same Markdown-plus-`$ARGUMENTS` shape as the canonical
    files, so the body passes through untouched.
    """
    target_root = workspace / ".opencode" / "commands"
    target_root.mkdir(parents=True, exist_ok=True)
    live: set[str] = set()
    installed = 0
    for source in _iter_entries(workspace / ".claude" / "commands"):
        if not source.is_file() or source.suffix != ".md":
            continue
        try:
            frontmatter, body = _frontmatter_and_body(source.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not body.strip():
            continue
        description = (
            frontmatter.get("description", "").strip() or f"Ciaobot /{source.stem} command"
        )
        target = target_root / f"{source.stem}.md"
        if _write_opencode_projection(
            target,
            [f"description: {json.dumps(description, ensure_ascii=False)}"],
            body,
        ):
            live.add(target.name)
            installed += 1
    return installed, _prune_opencode_dir(target_root, live)


def _install_opencode_mcps(workspace: Path) -> tuple[int, int]:
    """Project `.mcp.json` into `opencode.json`, preserving user-owned entries.

    JSON has no comment syntax, so a marker-fence approach does not transfer.
    Ciaobot instead records the server
    names it owns in `.opencode/.ciao-managed-mcps.json` and prunes only those.
    A name the user has defined themselves is never touched.
    """
    source = workspace / ".mcp.json"
    config_path = workspace / "opencode.json"
    sidecar = workspace / ".opencode" / OPENCODE_MANAGED_MCPS_FILE

    try:
        previous = set(json.loads(sidecar.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, TypeError):
        previous = set()

    desired: dict[str, dict] = {}
    if source.is_file():
        try:
            data = json.loads(source.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError, TypeError):
            print(
                f"WARN: invalid MCP config at {source}; opencode MCP sync skipped",
                file=sys.stderr,
            )
            return 0, 0
        servers: object = {}
        if isinstance(data, dict):
            servers = data.get("mcpServers") or data.get("mcp_servers") or {}
        if isinstance(servers, dict):
            for raw_name, meta in servers.items():
                name = str(raw_name).strip()
                if not name or name in OPENCODE_MCP_EXCLUDES or not isinstance(meta, dict):
                    continue
                entry = _opencode_mcp_entry(meta)
                if entry:
                    desired[name] = entry

    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        config = {}
    except (OSError, json.JSONDecodeError, TypeError):
        print(
            f"WARN: invalid {config_path}; opencode MCP sync skipped",
            file=sys.stderr,
        )
        return 0, 0
    if not isinstance(config, dict):
        return 0, 0

    existing = config.get("mcp")
    servers_out = dict(existing) if isinstance(existing, dict) else {}
    # Never clobber a server the user declared; only previously-managed names
    # are ours to rewrite or remove.
    installed = 0
    managed: set[str] = set()
    for name, entry in desired.items():
        if name in servers_out and name not in previous:
            continue
        servers_out[name] = entry
        # Only what we actually wrote goes in the sidecar. Recording every
        # *desired* name would claim ownership of the user's colliding entry,
        # and the very next sync would then overwrite it (and prune it once
        # `.mcp.json` dropped the name) — the guard above would last one run.
        managed.add(name)
        installed += 1
    pruned = 0
    for name in previous - set(desired):
        if servers_out.pop(name, None) is not None:
            pruned += 1

    config.setdefault("$schema", "https://opencode.ai/config.json")
    if servers_out:
        config["mcp"] = servers_out
    else:
        config.pop("mcp", None)

    rendered = json.dumps(config, indent=2, ensure_ascii=False) + "\n"
    try:
        if not config_path.exists() or config_path.read_text(encoding="utf-8") != rendered:
            config_path.write_text(rendered, encoding="utf-8")
        sidecar.parent.mkdir(parents=True, exist_ok=True)
        sidecar.write_text(
            json.dumps(sorted(managed), indent=2) + "\n", encoding="utf-8"
        )
    except OSError:
        return 0, 0
    return installed, pruned


def _opencode_mcp_entry(meta: dict) -> dict | None:
    """One `.mcp.json` server in opencode's `mcp` object shape.

    Credentials stay environment references: a literal value is dropped rather
    than copied into a tracked config file.
    """
    url = str(meta.get("url") or "").strip()
    if url:
        entry: dict = {"type": "remote", "url": url, "enabled": True}
        bearer_env = str(meta.get("bearer_token_env_var") or "").strip()
        bearer_env = bearer_env or _bearer_env_name(meta.get("headers"))
        if bearer_env:
            entry["headers"] = {"Authorization": f"Bearer {{env:{bearer_env}}}"}
        return entry
    command = str(meta.get("command") or "").strip()
    if not command:
        return None
    args = meta.get("args")
    args = [str(arg) for arg in args] if isinstance(args, list) else []
    entry = {"type": "local", "command": [command, *args], "enabled": True}
    env = meta.get("env")
    if isinstance(env, dict):
        environment = {
            str(key): _opencode_env_placeholder(value)
            for key, value in sorted(env.items(), key=lambda item: str(item[0]))
            if _opencode_env_placeholder(value)
        }
        if environment:
            entry["environment"] = environment
    return entry


def _canonical_agent_sources(workspace: Path) -> list[Path]:
    """Return canonical and packaged agent projections, excluding user-only Claude files."""
    result: list[Path] = []
    for source in _iter_entries(workspace / ".claude" / "agents"):
        if not source.is_file() or source.suffix != ".md":
            continue
        canonical = False
        if source.is_symlink():
            try:
                source.resolve().relative_to((workspace / "subagents").resolve())
                canonical = True
            except (OSError, ValueError):
                pass
        if canonical or _is_managed_stock_agent(source):
            result.append(source)
    return result


def _ensure_linked_workspace_guides(workspace: Path) -> None:
    """Expose one workspace guide through both CLI-native filenames.

    ``CLAUDE.md`` is the canonical editable file and ``AGENTS.md`` is a
    relative symlink to it. Existing user-authored AGENTS.md files (including
    custom symlinks) are preserved; only a missing file or Ciaobot's packaged
    stock copy is linked.
    """
    claude_guide = workspace / "CLAUDE.md"
    agents_guide = workspace / "AGENTS.md"
    try:
        from importlib import resources

        stock_workspace = resources.files("ciao.stock").joinpath("workspace")
        stock_agents = stock_workspace.joinpath("AGENTS.md")
        stock_claude = stock_workspace.joinpath("CLAUDE.md")

        if agents_guide.is_symlink():
            return
        if agents_guide.exists():
            if agents_guide.read_bytes() != stock_agents.read_bytes():
                return
            agents_guide.unlink()

        if not claude_guide.exists():
            with resources.as_file(stock_claude) as source:
                shutil.copy2(source, claude_guide)
        agents_guide.symlink_to(claude_guide.name)
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        return


def _resolve_vault_root(workspace: Path) -> Path:
    """Vault root for a workspace checkout, honouring the env override.

    Mirrors ``ciao.cli``'s resolution rather than building a ``CiaoConfig``: this
    runs inside skill sync, which must not fail because the wider config is
    mid-setup.
    """
    raw = os.environ.get("CIAO_VAULT_ROOT", "").strip() or "memory-vault"
    root = Path(raw).expanduser()
    return root if root.is_absolute() else workspace / root


def _configured_memory_char_limit(workspace: Path) -> int | None:
    """The effective ``CIAO_MEMORY_CHAR_LIMIT`` for cap-marker migration.

    Resolution order mirrors what the server does at start (dotenv loads
    without overriding exported variables): the process environment wins,
    then the nearest ``.env`` defining the variable — the workspace's own,
    walking up through owning directories (an install root that scaffolds
    per-workspace agent roots keeps its ``.env`` there, and ``ciao setup``
    re-scaffolding passes agent roots to sync without exporting its parsed
    values), bounded at four levels up — then ``None`` meaning "use
    memory_tool's shipped default". Each dotenv is parsed with python-dotenv
    itself (``dotenv_values``, which mutates nothing) so exactly the syntaxes
    the server accepts are honoured here — ``export`` prefixes, quoting,
    inline comments. Building no ``CiaoConfig`` matters: its constructor
    mutates shared env state mid-sync. Unparseable numeric values are
    ignored, falling through to the next source or the shipped default.
    """
    sources: list[str] = [os.environ.get("CIAO_MEMORY_CHAR_LIMIT", "").strip()]
    try:
        from dotenv import dotenv_values
    except ImportError:  # pragma: no cover - dotenv ships with the app
        logger.debug("memory: python-dotenv unavailable for cap migration")
        return None
    for ancestor in [workspace, *workspace.parents[:4]]:
        dotenv = ancestor / ".env"
        if not dotenv.exists():
            continue
        try:
            values = dotenv_values(dotenv) or {}
        except Exception:  # noqa: BLE001 — advisory migration must not block sync
            logger.debug(
                "memory: could not parse %s for cap migration",
                dotenv,
                exc_info=True,
            )
            continue
        raw = str(values.get("CIAO_MEMORY_CHAR_LIMIT", "") or "").strip()
        if raw:
            sources.append(raw)
            break
    for raw in sources:
        if raw:
            try:
                return int(raw)
            except ValueError:
                continue
    return None


def _resolve_runtime_root(workspace: Path) -> Path:
    raw = os.environ.get("CIAO_RUNTIME_ROOT", "").strip() or ".runtime"
    root = Path(raw).expanduser()
    return root if root.is_absolute() else workspace / root


def _any_workspace_has_gws_profile(config) -> bool:
    """Whether any registered workspace has a usable Google account.

    Used for the shared pre-re-root catalog, which one set of ``gws-*`` skills
    serves for every workspace. That catalog must stay populated if any
    workspace has a profile (the chats there set the linked ``GWS_PROFILE``),
    and only be gated off when none do.
    """
    try:
        from ciao.gws_auth import workspace_gws_profile  # noqa: PLC0415

        return any(
            workspace_gws_profile(config, name) != ""
            for name in config.workspace_names()
        )
    except Exception:
        return True


def _config_for_root(root: Path):
    """``CiaoConfig`` for the install that owns ``root``, or ``None``.

    Derives the install root from the supplied agent root rather than the
    ambient ``CIAO_WORKSPACE``/cwd, so a manual ``ciao sync-skills
    --workspace /path/to/install/workspace`` run from anywhere resolves the
    right registry. A post-re-root agent root is a child of the install root;
    a pre-re-root root IS the install root. The config is only accepted when
    it actually names ``root`` among its agent roots, so an unrelated install
    is never matched.

    The owning install is found with the side-effect-free ``agent_roots_for``
    probe first: ``CiaoConfig.from_env`` writes a session secret when
    ``PWA_AUTH_TOKEN`` is absent, so constructing it for a candidate that does
    not own ``root`` would create stray ``.runtime/session-secret`` files under
    both candidate roots before either is shown to be the owner. Only the
    confirmed owner gets a config built.
    """
    from ciao.config import agent_roots_for  # noqa: PLC0415

    candidates = [root.parent, root] if root.parent != root else [root]
    owner: Path | None = None
    for candidate in candidates:
        runtime = candidate / ".runtime"
        if not runtime.is_dir():
            continue
        try:
            targets = agent_roots_for(candidate, runtime)
        except Exception:
            continue
        if any(Path(r).resolve() == root.resolve() for r, _ in targets):
            # Prefer the re-rooted owner (root.parent) over the single-root
            # owner (root itself) when both name it.
            owner = candidate
            break
    if owner is None:
        return None

    env: dict[str, str] = {k: v for k, v in os.environ.items()}
    env["CIAO_WORKSPACE"] = str(owner)
    dotenv_path = owner / ".env"
    if dotenv_path.is_file():
        try:
            from dotenv import dotenv_values
            for key, value in (dotenv_values(dotenv_path) or {}).items():
                if value is not None and key not in env:
                    env[key] = value
        except Exception:  # noqa: BLE001 — env loading must not block sync
            logger.debug("sync: could not load %s", dotenv_path, exc_info=True)
    from ciao.config import CiaoConfig  # noqa: PLC0415

    try:
        return CiaoConfig.from_env(env)
    except Exception:
        return None


def resolve_workspace_skills_gws_gate(config, root: Path, workspace_name: str) -> str | None:
    """The ``gws-*`` gate for a sync target, aggregating when the root is shared.

    ``None`` means "no gate" (install the GWS skills), ``""`` means "no profile
    connected, skip them", and a non-empty slug installs them. On a pre-re-root
    install every workspace's ``agent_root`` resolves to the same install root,
    so the gate must consider ALL workspaces: unlinking one must not prune the
    shared catalog while another still links an account. On a re-rooted install
    each root is its own workspace and the gate is that workspace's profile.
    """
    try:
        if config.agent_root(workspace_name) == config.workspace_root:
            return "" if not _any_workspace_has_gws_profile(config) else None
    except Exception:
        pass
    from ciao.gws_auth import workspace_gws_profile  # noqa: PLC0415

    return workspace_gws_profile(config, workspace_name)


def _resolve_workspace_gws_profile(
    root: Path, workspace_name: str | None, gws_profile: str | None
) -> str | None:
    """The GWS profile to gate ``gws-*`` stock skills on, or ``None``.

    ``None`` means "no gate" (the caller predates the profile check, or this
    root cannot be tied to a registered workspace, or it is the shared
    pre-re-root catalog that any workspace may use), ``""`` means "no profile
    connected, skip GWS skills", and a non-empty slug installs them. Callers
    with a ``CiaoConfig`` pass ``workspace_name``/``gws_profile`` explicitly;
    the fallback here derives the config from ``root`` so CLI/startup sync
    still applies the rule from a root path alone.
    """
    if gws_profile is not None:
        return gws_profile
    config = _config_for_root(root)
    if config is None:
        return None
    if workspace_name is None:
        workspace_name = _resolve_root_workspace(root, config)
    if not workspace_name:
        # An empty name is the pre-re-root SHARED catalog, one skill set served
        # to every workspace. Gating it on a single (empty) name would prune the
        # gws-* skills even though a linked workspace relies on them, so the
        # whole catalog is kept unless no registered workspace has a profile.
        return "" if not _any_workspace_has_gws_profile(config) else None
    from ciao.gws_auth import workspace_gws_profile  # noqa: PLC0415

    return workspace_gws_profile(config, workspace_name)


def _resolve_root_workspace(root: Path, config=None) -> str | None:
    """Map an agent root back to its registered workspace name, if any.

    ``root`` is an agent root (``<install>/<name>`` after the re-rooting, or the
    install root itself before it). Reads the registry through ``CiaoConfig``
    derived from ``root``, which owns the pre-/post-re-rooting layout decision,
    so a re-rooted install resolves each named root and a single-root or
    unregistered install resolves to ``None``.
    """
    if config is None:
        config = _config_for_root(root)
    if config is None:
        return None
    try:
        for candidate, name in config.agent_root_targets():
            if Path(candidate).resolve() == root.resolve():
                return str(name) if name else None
    except Exception:
        return None
    return None


def sync_workspace_skills(
    workspace: Path | str,
    *,
    refresh_upstream: bool = True,
    runner=subprocess.run,
    gws_profile: str | None = None,
    workspace_name: str | None = None,
) -> SyncSkillsResult:
    root = Path(workspace).expanduser().resolve()
    _ensure_linked_workspace_guides(root)
    try:
        from ciao import job_runs
        from ciao.memory_tool import (
            default_memory_dir,
            ensure_regions,
            migrate_legacy_files,
            migrate_region_caps,
        )

        guide = root / "CLAUDE.md"
        # The legacy fold-in can only ever succeed once, so only pay for it
        # (and record a job run) while the old files are actually there.
        legacy_dir = default_memory_dir()
        if any((legacy_dir / name).is_file() for name in ("memory.md", "user.md")):
            with job_runs.track_sync(
                "memory_migration", "Legacy memory migration"
            ) as run:
                # migrate_legacy_files ensures the regions itself.
                migration = migrate_legacy_files(guide)
                run.extra["migrated"] = migration.get("migrated", [])
                if not migration.get("migrated"):
                    run.skip("no legacy memory files to migrate")
        else:
            ensure_regions(guide)
        # Restamp markers still carrying a former shipped default so the
        # guide every session loads advertises the cap the runtime enforces.
        # The effective limit is resolved here, not inside memory_tool: a
        # standalone `ciao sync-skills` never loads <root>/.env, and an
        # override that lives only there must beat the stamp like it beats
        # the runtime default after a server start.
        restamped = migrate_region_caps(
            guide, char_limit=_configured_memory_char_limit(root)
        )
        if restamped:
            logger.info(
                "memory: restamped region caps to current defaults in %s: %s",
                guide,
                ", ".join(restamped),
            )
    except Exception:  # noqa: BLE001 — never block skill sync on memory regions
        logger.exception(
            "memory region ensure/migrate failed for %s; continuing skill sync",
            root,
        )

    try:
        from ciao import job_runs
        from ciao.vault_migration import migrate_if_needed, read_receipt

        vault_root = _resolve_vault_root(root)
        runtime_root = _resolve_runtime_root(root)
        # Receipt-gated so an existing install pays for the vault scan once, not
        # on every boot. `vault-lint` starts reporting non-canonical types on
        # upgrade, so without this an existing vault would hand the user a
        # permanently failing `os-audit`.
        if read_receipt(runtime_root) is None:
            with job_runs.track_sync(
                "vault_vocabulary_migration", "Vault vocabulary migration"
            ) as run:
                summary = migrate_if_needed(vault_root, runtime_root)
                renamed = summary.get("renamed") or []
                unresolved = summary.get("unresolved") or {}
                run.extra["renamed"] = len(renamed)
                run.extra["unresolved"] = sorted(unresolved)
                if summary.get("skipped"):
                    run.skip(str(summary["skipped"]))
                elif not renamed and not unresolved:
                    run.skip("vault types already canonical")
    except Exception:  # noqa: BLE001 — never block skill sync on the vault
        logger.exception(
            "vault vocabulary migration failed for %s; continuing skill sync",
            root,
        )

    upstream_updated = 0
    upstream_pruned = 0

    legacy_codex_pruned = _cleanup_legacy_codex_projections(root)
    gws = _resolve_workspace_gws_profile(root, workspace_name, gws_profile)
    stock_installed, stock_pruned = _install_stock_skills(root, gws_profile=gws)
    custom_installed, custom_pruned = _rebuild_custom_skill_links(root)
    stock_agents_installed, stock_agents_pruned = _install_stock_agents(root)
    print(
        f"Skills: {stock_installed} stock skills installed ({stock_pruned} stale pruned), "
        f"{custom_installed} custom-skill symlinks rebuilt, "
        f"{custom_pruned} orphaned pruned."
    )
    if stock_agents_installed or stock_agents_pruned:
        print(
            f"Skills: {stock_agents_installed} stock agent(s) installed "
            f"({stock_agents_pruned} stale pruned)."
        )
    agents_installed, agents_pruned = _mirror_dir_symlinks(
        root / "subagents",
        root / ".claude" / "agents",
        glob_pattern="*.md",
        prune_regular=False,
    )
    stock_command_sync = _seed_stock_commands(root)
    if any(
        (
            stock_command_sync.seeded,
            stock_command_sync.refreshed,
            stock_command_sync.customised,
            stock_command_sync.pruned,
        )
    ):
        print(
            f"Skills: {stock_command_sync.seeded} stock command(s) seeded, "
            f"{stock_command_sync.refreshed} refreshed, "
            f"{stock_command_sync.customised} customised (left as-is), "
            f"{stock_command_sync.pruned} stale pruned."
        )
    commands_installed, commands_pruned = _mirror_dir_symlinks(
        root / "commands",
        root / ".claude" / "commands",
        glob_pattern="*.md",
        prune_regular=False,
    )
    # opencode reads .claude/skills, .agents/skills, AGENTS.md and CLAUDE.md
    # natively, so only commands, subagents, and MCP servers are projected.
    opencode_agents_installed, opencode_agents_pruned = _install_opencode_agents(root)
    opencode_commands_installed, opencode_commands_pruned = _install_opencode_commands(root)
    opencode_mcps_installed, opencode_mcps_pruned = _install_opencode_mcps(root)
    print(
        f"Skills: {agents_installed} custom-agent symlinks rebuilt, "
        f"{commands_installed} command links rebuilt; "
        f"{agents_pruned + commands_pruned} orphaned pruned."
    )
    if legacy_codex_pruned:
        print(f"Legacy Codex projections removed: {legacy_codex_pruned} marked artifact(s).")
    print(
        f"opencode: {opencode_agents_installed} subagent(s) and "
        f"{opencode_commands_installed} command(s) projected, "
        f"{opencode_mcps_installed} project MCP server(s) synced; "
        f"{opencode_agents_pruned + opencode_commands_pruned + opencode_mcps_pruned} "
        "stale pruned. Skills and instructions are read natively."
    )

    return SyncSkillsResult(
        custom_installed=custom_installed,
        custom_pruned=custom_pruned,
        upstream_updated=upstream_updated,
        upstream_pruned=upstream_pruned,
        agents_installed=agents_installed,
        agents_pruned=agents_pruned,
        commands_installed=commands_installed,
        commands_pruned=commands_pruned,
        stock_installed=stock_installed,
        stock_pruned=stock_pruned,
        stock_agents_installed=stock_agents_installed,
        stock_agents_pruned=stock_agents_pruned,
        stock_commands_seeded=stock_command_sync.seeded,
        stock_commands_refreshed=stock_command_sync.refreshed,
        stock_commands_customised=stock_command_sync.customised,
        stock_commands_pruned=stock_command_sync.pruned,
        legacy_codex_pruned=legacy_codex_pruned,
        opencode_agents_installed=opencode_agents_installed,
        opencode_agents_pruned=opencode_agents_pruned,
        opencode_commands_installed=opencode_commands_installed,
        opencode_commands_pruned=opencode_commands_pruned,
        opencode_mcps_installed=opencode_mcps_installed,
        opencode_mcps_pruned=opencode_mcps_pruned,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path("."),
        help="Workspace root. Defaults to current directory.",
    )
    parser.add_argument(
        "--skip-upstream",
        action="store_true",
        help="Deprecated: no-op. Skills are local folders under skills/; no remote refresh is performed.",
    )
    parser.add_argument("--verbose", action="store_true", help="Accepted for script compatibility.")
    args = parser.parse_args(list(argv) if argv is not None else None)
    sync_workspace_skills(args.workspace)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
