"""Install and mirror Ciaobot skills, commands, and agents."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from ciao import skills_sync


@dataclass(frozen=True)
class SyncSkillsResult:
    custom_installed: int = 0
    custom_pruned: int = 0
    upstream_updated: int = 0
    upstream_pruned: int = 0
    agents_installed: int = 0
    agents_pruned: int = 0
    commands_installed: int = 0
    commands_pruned: int = 0
    stock_installed: int = 0
    stock_pruned: int = 0
    stock_agents_installed: int = 0
    stock_agents_pruned: int = 0
    codex_skills_installed: int = 0
    codex_skills_pruned: int = 0
    codex_wrappers_installed: int = 0
    codex_wrappers_pruned: int = 0
    codex_agents_installed: int = 0
    codex_agents_pruned: int = 0


# Marker dropped into skills copied from ciao.stock so stale copies can be
# pruned when the packaged set changes or a workspace skill overrides them.
STOCK_SKILL_MARKER = ".ciao-stock-skill"
STOCK_AGENT_MARKER_SUFFIX = ".ciao-stock-agent"
CODEX_WRAPPER_MARKER = ".ciao-codex-wrapper"
CODEX_AGENT_MARKER = "# Generated by Ciaobot from a canonical subagent.\n"
CODEX_CONFIG_BEGIN = "# >>> CIAOBOT MANAGED CODEX AGENTS >>>"
CODEX_CONFIG_END = "# <<< CIAOBOT MANAGED CODEX AGENTS <<<"
_CODEX_AGENT_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")

# Legacy setup copies of agents removed from the stock ship set. Sync prunes
# these when they still live only under .claude/agents/ (no subagents/ copy).
LEGACY_REMOVED_STOCK_AGENTS = frozenset({
    "comment-analyzer",
    "doc-updater",
    "pr-test-analyzer",
    "silent-failure-hunter",
})


def _load_json(path: Path) -> dict:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _remove_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def _is_custom_skill_link(path: Path) -> bool:
    if not path.is_symlink():
        return False
    try:
        target = os.readlink(path)
    except OSError:
        return False
    return f"/skills/{path.name}" in target


def _ensure_symlink(source: Path, link: Path, *, relative_to: Path | None = None) -> bool:
    source = source.resolve()
    if link.exists():
        try:
            if link.resolve() == source:
                return True
        except OSError:
            pass
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        _remove_path(link)

    link.parent.mkdir(parents=True, exist_ok=True)
    target: Path | str = source
    if relative_to is not None:
        target = os.path.relpath(source, relative_to)
    link.symlink_to(target)
    return True


def _iter_entries(path: Path) -> list[Path]:
    if not path.is_dir():
        return []
    return sorted(path.iterdir(), key=lambda entry: entry.name)


def _active_upstream_lock(workspace: Path, lock: dict) -> dict:
    """Exclude locked packages shadowed by a workspace-owned skill."""
    skills = lock.get("skills")
    if not isinstance(skills, dict):
        return {**lock, "skills": {}}
    active = {
        name: entry
        for name, entry in skills.items()
        if not (workspace / "skills" / name / "SKILL.md").is_file()
    }
    return {**lock, "skills": active}


def _installed_upstream_names(workspace: Path, candidates: set[str]) -> set[str]:
    """Return locked-package names present in either provider catalog.

    The upstream ``skills`` CLI stores canonical package directories under
    ``.agents/skills`` and links provider-specific catalogs back to them.
    Older installs may instead have a canonical ``.claude/skills`` directory,
    so both layouts remain supported.
    """
    installed: set[str] = set()
    catalogs = (workspace / ".claude" / "skills", workspace / ".agents" / "skills")
    for name in candidates:
        if (workspace / "skills" / name / "SKILL.md").is_file():
            continue
        for catalog in catalogs:
            entry = catalog / name
            if (entry / STOCK_SKILL_MARKER).is_file():
                continue
            if (entry / "SKILL.md").is_file():
                installed.add(name)
                break
    return installed


def _remove_upstream_skill(workspace: Path, name: str) -> None:
    """Remove a locked package from both projections without touching overrides."""
    if (workspace / "skills" / name / "SKILL.md").is_file():
        return
    catalogs = (workspace / ".claude" / "skills", workspace / ".agents" / "skills")
    for catalog in catalogs:
        entry = catalog / name
        if (entry / STOCK_SKILL_MARKER).is_file():
            continue
        if entry.exists() or entry.is_symlink():
            _remove_path(entry)


def _update_upstream_skills(
    workspace: Path,
    names: Sequence[str],
    *,
    runner=subprocess.run,
) -> bool:
    if not names:
        return True
    print("Skills: updating changed/missing -> " + " ".join(names))
    try:
        result = runner(
            ["npx", "-y", "skills", "update", "-p", "-y", *names],
            cwd=workspace,
            text=True,
            capture_output=True,
            check=False,
        )
    except OSError as exc:
        print(f"WARN: skills update failed: {exc}", file=sys.stderr)
        return False
    if result.returncode != 0:
        print("WARN: skills update reported errors", file=sys.stderr)
        return False
    return True


def _restore_missing_upstream_skills(
    workspace: Path,
    lock: dict,
    names: Sequence[str],
    *,
    runner=subprocess.run,
) -> set[str]:
    """Re-add missing locked packages without refreshing installed ones."""
    lock_skills = lock.get("skills")
    if not isinstance(lock_skills, dict):
        return set()

    grouped: dict[str, list[str]] = {}
    for name in names:
        entry = lock_skills.get(name)
        if not isinstance(entry, dict) or not entry.get("source"):
            print(f"WARN: locked skill {name} has no install source", file=sys.stderr)
            continue
        source = str(entry["source"])
        if entry.get("ref"):
            source = f"{source}#{entry['ref']}"
        grouped.setdefault(source, []).append(name)

    restored: set[str] = set()
    for source, source_names in grouped.items():
        print("Skills: restoring missing -> " + " ".join(source_names))
        try:
            result = runner(
                [
                    "npx",
                    "-y",
                    "skills",
                    "add",
                    source,
                    "--skill",
                    *source_names,
                    "--agent",
                    "claude-code",
                    "-y",
                ],
                cwd=workspace,
                text=True,
                capture_output=True,
                check=False,
            )
        except OSError as exc:
            print(f"WARN: skills restore failed: {exc}", file=sys.stderr)
            continue
        if result.returncode != 0:
            print(
                "WARN: skills restore reported errors for " + " ".join(source_names),
                file=sys.stderr,
            )
            continue
        restored.update(source_names)
    return restored


def _refresh_upstream_skills(
    workspace: Path,
    *,
    runner=subprocess.run,
) -> tuple[int, int]:
    lockfile = workspace / "skills-lock.json"
    if not lockfile.is_file():
        print(f"Skills: {lockfile} missing, skipping upstream refresh.")
        return 0, 0

    cache_path = workspace / ".runtime" / "skills-sync-cache.json"
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    lock = _active_upstream_lock(workspace, _load_json(lockfile))
    cache = _load_json(cache_path)
    desired = skills_sync.desired_sources(lock)
    cached_skills = cache.get("skills")
    cached_names = set(cached_skills) if isinstance(cached_skills, dict) else set()
    known_names = set(desired) | cached_names
    installed = _installed_upstream_names(workspace, known_names)
    missing = sorted(set(desired) - installed)
    auto_update = os.environ.get(
        "CIAO_AUTO_UPDATE_GITHUB_SKILLS", "false"
    ).strip().lower() not in {"0", "false", "no", "off"}

    if not auto_update:
        if not missing:
            print("Skills: automatic GitHub updates disabled; locked skills are installed.")
            return 0, 0
        if shutil.which("npx") is None or shutil.which("git") is None:
            print(
                "WARN: npx or git not found, cannot install missing locked skills",
                file=sys.stderr,
            )
            return 0, 0
        print("Skills: automatic GitHub updates disabled; restoring missing locked skills.")
        restored = _restore_missing_upstream_skills(
            workspace, lock, missing, runner=runner
        )
        return len(restored), 0

    if shutil.which("npx") is None or shutil.which("git") is None:
        print("WARN: npx or git not found, skipping upstream skill refresh", file=sys.stderr)
        return 0, 0

    heads = skills_sync.remote_heads(set(skills_sync.desired_sources(lock).values()))
    plan = skills_sync.plan(lock, cache, heads, installed)

    for name in plan["to_prune"]:
        _remove_upstream_skill(workspace, name)

    missing_set = set(missing)
    changed = [name for name in plan["to_update"] if name not in missing_set]
    restored = _restore_missing_upstream_skills(
        workspace, lock, missing, runner=runner
    )
    updated = _update_upstream_skills(workspace, changed, runner=runner)
    if not plan["to_update"]:
        print("Skills: upstream unchanged, no fetch needed.")

    complete = updated and restored == missing_set
    if complete:
        cache_path.write_text(
            json.dumps(skills_sync.build_cache(lock, heads, cache), indent=2),
            encoding="utf-8",
        )
    refreshed = len(restored) + (len(changed) if updated else 0)
    return refreshed, len(plan["to_prune"])


def _install_stock_skills(workspace: Path) -> tuple[int, int]:
    """Copy packaged ``ciao.stock/skills`` into ``.claude/skills``.

    A workspace ``skills/<name>`` always wins over the packaged skill of the
    same name.  Copies carry ``STOCK_SKILL_MARKER`` so they are refreshed on
    every sync and pruned once they disappear from the package (or become
    shadowed by a workspace skill).
    """
    from importlib import resources

    claude_skills = workspace / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)
    custom_dir = workspace / "skills"

    try:
        stock_skills = resources.files("ciao.stock").joinpath("skills")
        entries = [entry for entry in stock_skills.iterdir() if entry.is_dir()]
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        entries = []

    installed = 0
    live: set[str] = set()
    for entry in sorted(entries, key=lambda item: item.name):
        if not entry.joinpath("SKILL.md").is_file():
            continue
        if (custom_dir / entry.name / "SKILL.md").is_file():
            continue  # workspace skill shadows the packaged one
        target = claude_skills / entry.name
        if target.is_symlink():
            continue  # user-managed link, leave it alone
        with resources.as_file(entry) as source:
            shutil.copytree(source, target, dirs_exist_ok=True)
        (target / STOCK_SKILL_MARKER).touch()
        live.add(entry.name)
        installed += 1

    pruned = 0
    for existing in _iter_entries(claude_skills):
        if existing.name in live or existing.is_symlink() or not existing.is_dir():
            continue
        if not (existing / STOCK_SKILL_MARKER).exists():
            continue
        shutil.rmtree(existing)
        pruned += 1
    return installed, pruned


def _rebuild_custom_skill_links(workspace: Path) -> tuple[int, int]:
    custom_dir = workspace / "skills"
    claude_skills = workspace / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)

    installed = 0
    if custom_dir.is_dir():
        for skill_dir in sorted(custom_dir.iterdir(), key=lambda entry: entry.name):
            if not skill_dir.is_dir():
                continue
            if not (skill_dir / "SKILL.md").is_file() or (skill_dir / "SKILL.md").stat().st_size == 0:
                continue
            target = claude_skills / skill_dir.name
            _ensure_symlink(skill_dir, target, relative_to=claude_skills)
            installed += 1

    pruned = 0
    for target in _iter_entries(claude_skills):
        if not target.is_symlink() or target.exists():
            continue
        try:
            current = os.readlink(target)
        except OSError:
            continue
        if "/skills/" not in current:
            continue
        target.unlink(missing_ok=True)
        pruned += 1
    return installed, pruned


def _stock_agent_marker(agent_path: Path) -> Path:
    return agent_path.with_name(agent_path.name + STOCK_AGENT_MARKER_SUFFIX)


def _is_managed_stock_agent(agent_path: Path) -> bool:
    return _stock_agent_marker(agent_path).is_file()


def _mark_stock_agent(agent_path: Path) -> None:
    _stock_agent_marker(agent_path).touch()


def _unmark_stock_agent(agent_path: Path) -> None:
    _stock_agent_marker(agent_path).unlink(missing_ok=True)


def _install_stock_agents(workspace: Path) -> tuple[int, int]:
    """Copy packaged ``ciao.stock/agents`` into ``.claude/agents``.

    A workspace ``subagents/<name>.md`` always wins over the packaged agent of
    the same name. Copies carry a sibling ``*.ciao-stock-agent`` marker so they
    are refreshed on every sync and pruned once they disappear from the package
    (or become shadowed by a workspace subagent).
    """
    from importlib import resources

    agents_dir = workspace / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    custom_dir = workspace / "subagents"

    try:
        stock_agents = resources.files("ciao.stock").joinpath("agents")
        stock_files = sorted(
            (entry for entry in stock_agents.iterdir() if entry.name.endswith(".md")),
            key=lambda item: item.name,
        )
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        stock_files = []

    installed = 0
    live: set[str] = set()
    for stock_entry in stock_files:
        name = stock_entry.name
        if (custom_dir / name).is_file():
            continue  # workspace subagent shadows the packaged agent
        target = agents_dir / name
        if target.is_symlink():
            continue  # user-managed link, leave it alone
        with resources.as_file(stock_entry) as stock_path:
            shutil.copy2(stock_path, target)
        _mark_stock_agent(target)
        live.add(name)
        installed += 1

    pruned = 0
    for existing in _iter_entries(agents_dir):
        if not existing.is_file() or existing.name.endswith(STOCK_AGENT_MARKER_SUFFIX):
            continue
        if not existing.name.endswith(".md") or existing.is_symlink():
            continue
        if existing.name in live:
            continue
        if _is_managed_stock_agent(existing):
            _remove_path(existing)
            _unmark_stock_agent(existing)
            pruned += 1
            continue
        if (
            existing.stem in LEGACY_REMOVED_STOCK_AGENTS
            and not (custom_dir / existing.name).is_file()
        ):
            _remove_path(existing)
            pruned += 1

    for marker in agents_dir.glob(f"*{STOCK_AGENT_MARKER_SUFFIX}"):
        agent_path = marker.with_name(marker.name[: -len(STOCK_AGENT_MARKER_SUFFIX)])
        if agent_path.name not in live and not agent_path.exists():
            marker.unlink(missing_ok=True)

    return installed, pruned


def _seed_stock_commands(workspace: Path) -> int:
    """Ensure packaged commands live in canonical ``commands/``.

    Fresh installs seed from ``ciao.stock/commands``. Older workspaces that
    still have stock copies only under ``.claude/commands/`` are migrated
    into ``commands/`` so they become editable and covered by weekly-review
    hygiene checks.
    """
    from importlib import resources

    commands_dir = workspace / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)
    claude_commands = workspace / ".claude" / "commands"

    try:
        stock_commands = resources.files("ciao.stock").joinpath("commands")
        stock_files = sorted(
            (entry for entry in stock_commands.iterdir() if entry.name.endswith(".md")),
            key=lambda item: item.name,
        )
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        return 0

    seeded = 0
    for stock_entry in stock_files:
        canonical = commands_dir / stock_entry.name
        if canonical.exists():
            continue
        legacy = claude_commands / stock_entry.name
        with resources.as_file(stock_entry) as stock_path:
            stock_text = stock_path.read_text(encoding="utf-8")
            if legacy.is_file() and not legacy.is_symlink():
                # Legacy stock installs lived only under .claude/commands/ and
                # were not editable in Settings — seed the packaged revision.
                canonical.write_text(stock_text, encoding="utf-8")
            else:
                shutil.copy2(stock_path, canonical)
        seeded += 1
    return seeded


def _mirror_dir_symlinks(
    source_dir: Path,
    dest_dir: Path,
    *,
    glob_pattern: str = "*",
    prune_regular: bool,
) -> tuple[int, int]:
    dest_dir.mkdir(parents=True, exist_ok=True)
    linked = 0
    live: set[str] = set()
    if source_dir.is_dir():
        for entry in sorted(source_dir.glob(glob_pattern), key=lambda item: item.name):
            if not entry.exists():
                if entry.is_symlink():
                    print(
                        f"WARN: skipping dangling symlink {entry} -> {os.readlink(entry)}",
                        file=sys.stderr,
                    )
                continue
            live.add(entry.name)
            _ensure_symlink(entry, dest_dir / entry.name)
            linked += 1

    pruned = 0
    for entry in _iter_entries(dest_dir):
        if entry.name in live:
            continue
        if not prune_regular and not entry.is_symlink():
            continue
        _remove_path(entry)
        pruned += 1
    return linked, pruned


def _frontmatter_and_body(text: str) -> tuple[dict[str, str], str]:
    from ciao.web.commands import _FRONTMATTER_RE, _parse_frontmatter

    return _parse_frontmatter(text), _FRONTMATTER_RE.sub("", text, count=1).strip()


def _install_codex_wrappers(workspace: Path) -> tuple[int, int]:
    """Expose Ciaobot commands and named subagents as Codex workspace skills."""
    target_root = workspace / ".agents" / "skills"
    target_root.mkdir(parents=True, exist_ok=True)
    live: set[str] = set()
    installed = 0
    sources = (
        (workspace / ".claude" / "commands", "command", "*.md"),
        (workspace / ".claude" / "agents", "agent", "*.md"),
    )
    for source_root, kind, pattern in sources:
        for source in _iter_entries(source_root):
            if not source.is_file() or not source.match(pattern):
                continue
            name = f"ciao-{kind}-{source.stem}"
            target = target_root / name
            marker = target / CODEX_WRAPPER_MARKER
            if target.exists() and not marker.exists():
                continue  # never overwrite a user-managed Codex skill
            try:
                frontmatter, body = _frontmatter_and_body(
                    source.read_text(encoding="utf-8")
                )
            except OSError:
                continue
            description = frontmatter.get("description", "").strip()
            if not description:
                description = (
                    f"Run the Ciaobot /{source.stem} workspace command."
                    if kind == "command"
                    else f"Delegate suitable work to the Ciaobot {source.stem} role."
                )
            if kind == "command":
                preface = (
                    f"# /{source.stem}\n\n"
                    "Treat the text following this skill invocation as the command "
                    "arguments. Apply the workflow below, replacing `$ARGUMENTS` "
                    "with those arguments.\n\n"
                )
            else:
                preface = (
                    f"# {source.stem} agent role\n\n"
                    "When delegation is useful, spawn a Codex agent with the role "
                    "instructions below and synthesize its result. Otherwise apply "
                    "the instructions directly.\n\n"
                )
            target.mkdir(parents=True, exist_ok=True)
            (target / "SKILL.md").write_text(
                "---\n"
                f"name: {name}\n"
                f"description: {json.dumps(description, ensure_ascii=False)}\n"
                "---\n\n"
                + preface
                + body
                + "\n",
                encoding="utf-8",
            )
            marker.touch()
            live.add(name)
            installed += 1

    pruned = 0
    for target in _iter_entries(target_root):
        if target.name in live or not target.is_dir():
            continue
        if (target / CODEX_WRAPPER_MARKER).exists():
            shutil.rmtree(target)
            pruned += 1
    return installed, pruned


def _without_managed_codex_config(text: str) -> tuple[str, bool]:
    """Remove Ciaobot's prior agent-registration block from TOML text."""
    start = text.find(CODEX_CONFIG_BEGIN)
    if start < 0:
        return text, False
    end = text.find(CODEX_CONFIG_END, start)
    if end < 0:
        # A partial marker may be user-edited or truncated. Refuse to guess.
        return text, True
    end += len(CODEX_CONFIG_END)
    if end < len(text) and text[end] == "\n":
        end += 1
    return (text[:start].rstrip() + "\n" + text[end:].lstrip()).strip() + "\n", False


def _codex_agent_sources(workspace: Path) -> list[Path]:
    """Return canonical and packaged agent projections, excluding user-only Claude files."""
    result: list[Path] = []
    for source in _iter_entries(workspace / ".claude" / "agents"):
        if not source.is_file() or source.suffix != ".md":
            continue
        canonical = False
        if source.is_symlink():
            try:
                source.resolve().relative_to((workspace / "subagents").resolve())
                canonical = True
            except (OSError, ValueError):
                pass
        if canonical or _is_managed_stock_agent(source):
            result.append(source)
    return result


def _install_codex_agents(workspace: Path) -> tuple[int, int]:
    """Compile canonical Ciaobot roles into Codex native agent definitions.

    The generated files and the marked block in ``.codex/config.toml`` are
    fully Ciaobot-owned. Unmarked TOML and user-declared agent names are never
    rewritten; a name collision simply leaves the user's definition in force.
    """
    config_path = workspace / ".codex" / "config.toml"
    try:
        original = config_path.read_text(encoding="utf-8")
    except FileNotFoundError:
        original = ""
    except OSError:
        return 0, 0
    unmanaged, partial_marker = _without_managed_codex_config(original)
    if partial_marker:
        print(
            f"WARN: incomplete Ciaobot marker in {config_path}; native Codex agents not changed",
            file=sys.stderr,
        )
        return 0, 0
    try:
        parsed = tomllib.loads(unmanaged) if unmanaged.strip() else {}
    except tomllib.TOMLDecodeError as exc:
        print(
            f"WARN: invalid user-owned Codex config {config_path}: {exc}; native agents not changed",
            file=sys.stderr,
        )
        return 0, 0
    user_agents = parsed.get("agents") if isinstance(parsed, dict) else None
    conflicts = set(user_agents) if isinstance(user_agents, dict) else set()

    target_root = workspace / ".codex" / "agents"
    target_root.mkdir(parents=True, exist_ok=True)
    live: set[str] = set()
    registrations: list[tuple[str, str]] = []
    installed = 0
    for source in _codex_agent_sources(workspace):
        name = source.stem
        if not _CODEX_AGENT_NAME_RE.fullmatch(name) or name in conflicts:
            continue
        try:
            frontmatter, body = _frontmatter_and_body(source.read_text(encoding="utf-8"))
        except OSError:
            continue
        instructions = body.strip()
        if not instructions:
            continue
        description = frontmatter.get("description", "").strip() or f"Ciaobot {name} role"
        target = target_root / f"{name}.toml"
        if target.exists():
            try:
                existing = target.read_text(encoding="utf-8")
            except OSError:
                continue
            if not existing.startswith(CODEX_AGENT_MARKER):
                continue
        target.write_text(
            CODEX_AGENT_MARKER
            + "# Edit the source under subagents/ (or the packaged stock role), then run ciao sync-skills.\n"
            + f"developer_instructions = {json.dumps(instructions, ensure_ascii=False)}\n",
            encoding="utf-8",
        )
        live.add(target.name)
        registrations.append((name, description))
        installed += 1

    pruned = 0
    for target in _iter_entries(target_root):
        if target.name in live or not target.is_file() or target.suffix != ".toml":
            continue
        try:
            managed = target.read_text(encoding="utf-8").startswith(CODEX_AGENT_MARKER)
        except OSError:
            continue
        if managed:
            target.unlink()
            pruned += 1

    block_lines = [CODEX_CONFIG_BEGIN]
    for name, description in registrations:
        block_lines.extend([
            f"[agents.{json.dumps(name, ensure_ascii=False)}]",
            f"description = {json.dumps(description, ensure_ascii=False)}",
            f"config_file = {json.dumps(f'agents/{name}.toml')}",
            "",
        ])
    block_lines.append(CODEX_CONFIG_END)
    block = "\n".join(block_lines) + "\n"
    updated = (unmanaged.rstrip() + "\n\n" if unmanaged.strip() else "") + block
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(updated, encoding="utf-8")
    return installed, pruned


def _ensure_linked_workspace_guides(workspace: Path) -> None:
    """Expose one workspace guide through both CLI-native filenames.

    ``CLAUDE.md`` is the canonical editable file and ``AGENTS.md`` is a
    relative symlink to it. Existing user-authored AGENTS.md files (including
    custom symlinks) are preserved; only a missing file or Ciaobot's packaged
    stock copy is linked.
    """
    claude_guide = workspace / "CLAUDE.md"
    codex_guide = workspace / "AGENTS.md"
    try:
        from importlib import resources

        stock_workspace = resources.files("ciao.stock").joinpath("workspace")
        stock_agents = stock_workspace.joinpath("AGENTS.md")
        stock_claude = stock_workspace.joinpath("CLAUDE.md")

        if codex_guide.is_symlink():
            return
        if codex_guide.exists():
            if codex_guide.read_bytes() != stock_agents.read_bytes():
                return
            codex_guide.unlink()

        if not claude_guide.exists():
            with resources.as_file(stock_claude) as source:
                shutil.copy2(source, claude_guide)
        codex_guide.symlink_to(claude_guide.name)
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        return


def sync_workspace_skills(
    workspace: Path | str,
    *,
    refresh_upstream: bool = True,
    runner=subprocess.run,
) -> SyncSkillsResult:
    root = Path(workspace).expanduser().resolve()
    _ensure_linked_workspace_guides(root)

    upstream_updated = 0
    upstream_pruned = 0
    if refresh_upstream:
        upstream_updated, upstream_pruned = _refresh_upstream_skills(root, runner=runner)

    stock_installed, stock_pruned = _install_stock_skills(root)
    custom_installed, custom_pruned = _rebuild_custom_skill_links(root)
    stock_agents_installed, stock_agents_pruned = _install_stock_agents(root)
    print(
        f"Skills: {stock_installed} stock skills installed ({stock_pruned} stale pruned), "
        f"{custom_installed} custom-skill symlinks rebuilt, "
        f"{custom_pruned} orphaned pruned."
    )
    if stock_agents_installed or stock_agents_pruned:
        print(
            f"Skills: {stock_agents_installed} stock agent(s) installed "
            f"({stock_agents_pruned} stale pruned)."
        )
    agents_installed, agents_pruned = _mirror_dir_symlinks(
        root / "subagents",
        root / ".claude" / "agents",
        glob_pattern="*.md",
        prune_regular=False,
    )
    stock_commands_seeded = _seed_stock_commands(root)
    if stock_commands_seeded:
        print(f"Skills: {stock_commands_seeded} stock command(s) seeded into commands/.")
    commands_installed, commands_pruned = _mirror_dir_symlinks(
        root / "commands",
        root / ".claude" / "commands",
        glob_pattern="*.md",
        prune_regular=False,
    )
    codex_skills_installed, codex_skills_pruned = _mirror_dir_symlinks(
        root / ".claude" / "skills",
        root / ".agents" / "skills",
        prune_regular=False,
    )
    codex_wrappers_installed, codex_wrappers_pruned = _install_codex_wrappers(root)
    codex_agents_installed, codex_agents_pruned = _install_codex_agents(root)
    print(
        f"Skills: {agents_installed} agent links, {commands_installed} command links rebuilt; "
        f"{agents_pruned + commands_pruned} orphaned pruned."
    )
    print(
        f"Codex: {codex_skills_installed} skill links and "
        f"{codex_wrappers_installed} command/agent wrappers installed; "
        f"{codex_skills_pruned + codex_wrappers_pruned} stale pruned."
    )
    print(
        f"Codex: {codex_agents_installed} native agent definitions installed; "
        f"{codex_agents_pruned} stale pruned."
    )

    return SyncSkillsResult(
        custom_installed=custom_installed,
        custom_pruned=custom_pruned,
        upstream_updated=upstream_updated,
        upstream_pruned=upstream_pruned,
        agents_installed=agents_installed,
        agents_pruned=agents_pruned,
        commands_installed=commands_installed,
        commands_pruned=commands_pruned,
        stock_installed=stock_installed,
        stock_pruned=stock_pruned,
        stock_agents_installed=stock_agents_installed,
        stock_agents_pruned=stock_agents_pruned,
        codex_skills_installed=codex_skills_installed,
        codex_skills_pruned=codex_skills_pruned,
        codex_wrappers_installed=codex_wrappers_installed,
        codex_wrappers_pruned=codex_wrappers_pruned,
        codex_agents_installed=codex_agents_installed,
        codex_agents_pruned=codex_agents_pruned,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path("."),
        help="Workspace root. Defaults to current directory.",
    )
    parser.add_argument(
        "--skip-upstream",
        action="store_true",
        help="Skip skills-lock.json remote refresh and only mirror local catalogs.",
    )
    parser.add_argument("--verbose", action="store_true", help="Accepted for script compatibility.")
    args = parser.parse_args(list(argv) if argv is not None else None)
    sync_workspace_skills(
        args.workspace,
        refresh_upstream=not args.skip_upstream,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
