"""Install and mirror Ciaobot skills, commands, agents, and MCP servers."""

from __future__ import annotations

import argparse
import json
import logging
from ciao.jsonio import read_json_dict
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Sequence

from ciao import skills_sync

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SyncSkillsResult:
    custom_installed: int = 0
    custom_pruned: int = 0
    upstream_updated: int = 0
    upstream_pruned: int = 0
    agents_installed: int = 0
    agents_pruned: int = 0
    commands_installed: int = 0
    commands_pruned: int = 0
    stock_installed: int = 0
    stock_pruned: int = 0
    stock_agents_installed: int = 0
    stock_agents_pruned: int = 0
    legacy_codex_pruned: int = 0
    # opencode needs no skill or instruction projection: it discovers
    # `.claude/skills`, `.agents/skills`, `AGENTS.md`, and `CLAUDE.md` natively.
    opencode_agents_installed: int = 0
    opencode_agents_pruned: int = 0
    opencode_commands_installed: int = 0
    opencode_commands_pruned: int = 0
    opencode_mcps_installed: int = 0
    opencode_mcps_pruned: int = 0


# Bound the upstream `npx skills ...` calls. `npx -y` cold-downloads the
# `skills` package and then does network git fetches; with no timeout a stall
# (cold cache, slow/blocked network, an interactive prompt) hangs the
# `update_skills` startup phase forever, which pins the boot overlay on
# "booting" (overall_ready never flips). Bounded so the phase always ends.
SKILLS_NPX_TIMEOUT = 180.0
# Marker dropped into skills copied from ciao.stock so stale copies can be
# pruned when the packaged set changes or a workspace skill overrides them.
STOCK_SKILL_MARKER = ".ciao-stock-skill"
STOCK_AGENT_MARKER_SUFFIX = ".ciao-stock-agent"
CODEX_WRAPPER_MARKER = ".ciao-codex-wrapper"
CODEX_AGENT_MARKER = "# Generated by Ciaobot from a canonical subagent.\n"
CODEX_CONFIG_BEGIN = "# >>> CIAOBOT MANAGED CODEX AGENTS >>>"
CODEX_CONFIG_END = "# <<< CIAOBOT MANAGED CODEX AGENTS <<<"
CODEX_MCP_CONFIG_BEGIN = "# >>> CIAOBOT MANAGED PROJECT MCPS >>>"
CODEX_MCP_CONFIG_END = "# <<< CIAOBOT MANAGED PROJECT MCPS <<<"
_AGENT_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]*$")

# opencode projections. Skills and instructions need none: opencode discovers
# `.claude/skills/<name>/SKILL.md`, `.agents/skills/<name>/SKILL.md`,
# `AGENTS.md`, and `CLAUDE.md` natively (verified against opencode 1.18).
# Only commands, subagents, and MCP servers need generated files.
#
# Markdown carries its marker as an HTML comment under the frontmatter; JSON
# has no comment syntax, so managed MCP server names are tracked in a sidecar
# and only those are ever pruned from `opencode.json`.
OPENCODE_GENERATED_MARKER = (
    "<!-- Generated by Ciaobot. Edit the canonical source, then run ciao sync-skills. -->"
)
OPENCODE_MANAGED_MCPS_FILE = ".ciao-managed-mcps.json"
OPENCODE_MCP_EXCLUDES = frozenset({"ciaobot", "ciaobot-fastmcp"})

# Legacy setup copies of agents removed from the stock ship set. Sync prunes
# these when they still live only under .claude/agents/ (no subagents/ copy).
LEGACY_REMOVED_STOCK_AGENTS = frozenset({
    "comment-analyzer",
    "doc-updater",
    "pr-test-analyzer",
    "silent-failure-hunter",
})


def _load_json(path: Path) -> dict:
    try:
        data = read_json_dict(path)
        return data
    except (FileNotFoundError, json.JSONDecodeError):
        return {}


def _remove_path(path: Path) -> None:
    if path.is_dir() and not path.is_symlink():
        shutil.rmtree(path)
    else:
        path.unlink(missing_ok=True)


def _is_custom_skill_link(path: Path) -> bool:
    if not path.is_symlink():
        return False
    try:
        target = os.readlink(path)
    except OSError:
        return False
    return f"/skills/{path.name}" in target


def _ensure_symlink(source: Path, link: Path, *, relative_to: Path | None = None) -> bool:
    source = source.resolve()
    if link.exists():
        try:
            if link.resolve() == source:
                return True
        except OSError:
            pass
    if link.is_symlink():
        link.unlink()
    elif link.exists():
        _remove_path(link)

    link.parent.mkdir(parents=True, exist_ok=True)
    target: Path | str = source
    if relative_to is not None:
        target = os.path.relpath(source, relative_to)
    link.symlink_to(target)
    return True


def _iter_entries(path: Path) -> list[Path]:
    if not path.is_dir():
        return []
    return sorted(path.iterdir(), key=lambda entry: entry.name)


def _active_upstream_lock(workspace: Path, lock: dict) -> dict:
    """Exclude locked packages shadowed by a workspace-owned skill."""
    skills = lock.get("skills")
    if not isinstance(skills, dict):
        return {**lock, "skills": {}}
    active = {
        name: entry
        for name, entry in skills.items()
        if not (workspace / "skills" / name / "SKILL.md").is_file()
    }
    return {**lock, "skills": active}


def _installed_upstream_names(workspace: Path, candidates: set[str]) -> set[str]:
    """Return locked-package names present in either provider catalog.

    The upstream ``skills`` CLI stores canonical package directories under
    ``.agents/skills`` and links provider-specific catalogs back to them.
    Older installs may instead have a canonical ``.claude/skills`` directory,
    so both layouts remain supported.
    """
    installed: set[str] = set()
    catalogs = (workspace / ".claude" / "skills", workspace / ".agents" / "skills")
    for name in candidates:
        if (workspace / "skills" / name / "SKILL.md").is_file():
            continue
        for catalog in catalogs:
            entry = catalog / name
            if (entry / STOCK_SKILL_MARKER).is_file():
                continue
            if (entry / "SKILL.md").is_file():
                installed.add(name)
                break
    return installed


def _remove_upstream_skill(workspace: Path, name: str) -> None:
    """Remove a locked package from both projections without touching overrides."""
    if (workspace / "skills" / name / "SKILL.md").is_file():
        return
    catalogs = (workspace / ".claude" / "skills", workspace / ".agents" / "skills")
    for catalog in catalogs:
        entry = catalog / name
        if (entry / STOCK_SKILL_MARKER).is_file():
            continue
        if entry.exists() or entry.is_symlink():
            _remove_path(entry)


def _update_upstream_skills(
    workspace: Path,
    names: Sequence[str],
    *,
    runner=subprocess.run,
) -> bool:
    if not names:
        return True
    print("Skills: updating changed/missing -> " + " ".join(names))
    try:
        result = runner(
            ["npx", "-y", "skills", "update", "-p", "-y", *names],
            cwd=workspace,
            text=True,
            capture_output=True,
            check=False,
            timeout=SKILLS_NPX_TIMEOUT,
        )
    except subprocess.TimeoutExpired:
        print(
            f"WARN: skills update timed out after {SKILLS_NPX_TIMEOUT:.0f}s",
            file=sys.stderr,
        )
        return False
    except OSError as exc:
        print(f"WARN: skills update failed: {exc}", file=sys.stderr)
        return False
    if result.returncode != 0:
        print("WARN: skills update reported errors", file=sys.stderr)
        return False
    return True


def _restore_missing_upstream_skills(
    workspace: Path,
    lock: dict,
    names: Sequence[str],
    *,
    runner=subprocess.run,
) -> set[str]:
    """Re-add missing locked packages without refreshing installed ones."""
    lock_skills = lock.get("skills")
    if not isinstance(lock_skills, dict):
        return set()

    grouped: dict[str, list[str]] = {}
    for name in names:
        entry = lock_skills.get(name)
        if not isinstance(entry, dict) or not entry.get("source"):
            print(f"WARN: locked skill {name} has no install source", file=sys.stderr)
            continue
        source = str(entry["source"])
        if entry.get("ref"):
            source = f"{source}#{entry['ref']}"
        grouped.setdefault(source, []).append(name)

    restored: set[str] = set()
    for source, source_names in grouped.items():
        print("Skills: restoring missing -> " + " ".join(source_names))
        try:
            result = runner(
                [
                    "npx",
                    "-y",
                    "skills",
                    "add",
                    source,
                    "--skill",
                    *source_names,
                    "--agent",
                    "claude-code",
                    "-y",
                ],
                cwd=workspace,
                text=True,
                capture_output=True,
                check=False,
                timeout=SKILLS_NPX_TIMEOUT,
            )
        except subprocess.TimeoutExpired:
            print(
                "WARN: skills restore timed out after "
                f"{SKILLS_NPX_TIMEOUT:.0f}s for " + " ".join(source_names),
                file=sys.stderr,
            )
            continue
        except OSError as exc:
            print(f"WARN: skills restore failed: {exc}", file=sys.stderr)
            continue
        if result.returncode != 0:
            print(
                "WARN: skills restore reported errors for " + " ".join(source_names),
                file=sys.stderr,
            )
            continue
        restored.update(source_names)
    return restored


def _refresh_upstream_skills(
    workspace: Path,
    *,
    runner=subprocess.run,
) -> tuple[int, int]:
    lockfile = workspace / "skills-lock.json"
    if not lockfile.is_file():
        print(f"Skills: {lockfile} missing, skipping upstream refresh.")
        return 0, 0

    cache_path = workspace / ".runtime" / "skills-sync-cache.json"
    cache_path.parent.mkdir(parents=True, exist_ok=True)
    lock = _active_upstream_lock(workspace, _load_json(lockfile))
    cache = _load_json(cache_path)
    desired = skills_sync.desired_sources(lock)
    cached_skills = cache.get("skills")
    cached_names = set(cached_skills) if isinstance(cached_skills, dict) else set()
    known_names = set(desired) | cached_names
    installed = _installed_upstream_names(workspace, known_names)
    missing = sorted(set(desired) - installed)
    auto_update = os.environ.get(
        "CIAO_AUTO_UPDATE_GITHUB_SKILLS", "false"
    ).strip().lower() not in {"0", "false", "no", "off"}

    if not auto_update:
        if not missing:
            print("Skills: automatic GitHub updates disabled; locked skills are installed.")
            return 0, 0
        if shutil.which("npx") is None or shutil.which("git") is None:
            print(
                "WARN: npx or git not found, cannot install missing locked skills",
                file=sys.stderr,
            )
            return 0, 0
        print("Skills: automatic GitHub updates disabled; restoring missing locked skills.")
        restored = _restore_missing_upstream_skills(
            workspace, lock, missing, runner=runner
        )
        return len(restored), 0

    if shutil.which("npx") is None or shutil.which("git") is None:
        print("WARN: npx or git not found, skipping upstream skill refresh", file=sys.stderr)
        return 0, 0

    heads = skills_sync.remote_heads(set(skills_sync.desired_sources(lock).values()))
    plan = skills_sync.plan(lock, cache, heads, installed)

    for name in plan["to_prune"]:
        _remove_upstream_skill(workspace, name)

    missing_set = set(missing)
    changed = [name for name in plan["to_update"] if name not in missing_set]
    restored = _restore_missing_upstream_skills(
        workspace, lock, missing, runner=runner
    )
    updated = _update_upstream_skills(workspace, changed, runner=runner)
    if not plan["to_update"]:
        print("Skills: upstream unchanged, no fetch needed.")

    complete = updated and restored == missing_set
    if complete:
        cache_path.write_text(
            json.dumps(skills_sync.build_cache(lock, heads, cache), indent=2),
            encoding="utf-8",
        )
    refreshed = len(restored) + (len(changed) if updated else 0)
    return refreshed, len(plan["to_prune"])


def _install_stock_skills(workspace: Path) -> tuple[int, int]:
    """Copy packaged ``ciao.stock/skills`` into ``.claude/skills``.

    A workspace ``skills/<name>`` always wins over the packaged skill of the
    same name.  Copies carry ``STOCK_SKILL_MARKER`` so they are refreshed on
    every sync and pruned once they disappear from the package (or become
    shadowed by a workspace skill).
    """
    from importlib import resources

    claude_skills = workspace / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)
    custom_dir = workspace / "skills"

    try:
        stock_skills = resources.files("ciao.stock").joinpath("skills")
        entries = [entry for entry in stock_skills.iterdir() if entry.is_dir()]
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        entries = []

    installed = 0
    live: set[str] = set()
    for entry in sorted(entries, key=lambda item: item.name):
        if not entry.joinpath("SKILL.md").is_file():
            continue
        if (custom_dir / entry.name / "SKILL.md").is_file():
            continue  # workspace skill shadows the packaged one
        target = claude_skills / entry.name
        if target.is_symlink():
            continue  # user-managed link, leave it alone
        with resources.as_file(entry) as source:
            shutil.copytree(source, target, dirs_exist_ok=True)
        (target / STOCK_SKILL_MARKER).touch()
        live.add(entry.name)
        installed += 1

    pruned = 0
    for existing in _iter_entries(claude_skills):
        if existing.name in live or existing.is_symlink() or not existing.is_dir():
            continue
        if not (existing / STOCK_SKILL_MARKER).exists():
            continue
        shutil.rmtree(existing)
        pruned += 1
    return installed, pruned


def _rebuild_custom_skill_links(workspace: Path) -> tuple[int, int]:
    custom_dir = workspace / "skills"
    claude_skills = workspace / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)

    installed = 0
    if custom_dir.is_dir():
        for skill_dir in sorted(custom_dir.iterdir(), key=lambda entry: entry.name):
            if not skill_dir.is_dir():
                continue
            if not (skill_dir / "SKILL.md").is_file() or (skill_dir / "SKILL.md").stat().st_size == 0:
                continue
            target = claude_skills / skill_dir.name
            _ensure_symlink(skill_dir, target, relative_to=claude_skills)
            installed += 1

    pruned = 0
    for target in _iter_entries(claude_skills):
        if not target.is_symlink() or target.exists():
            continue
        try:
            current = os.readlink(target)
        except OSError:
            continue
        if "/skills/" not in current:
            continue
        target.unlink(missing_ok=True)
        pruned += 1
    return installed, pruned


def mirror_shared_skill_sources(workspace: Path, shared_root: Path) -> tuple[int, int]:
    """Link every skill in a shared source directory into one root's catalog.

    ``<install>/skills-src/`` is a mirror source, not a workspace: it has no
    vault, no guide and no sessions of its own. A skill placed there applies in
    every agent root, so each root gets a symlink rather than a copy — one edit,
    N roots, and no divergence to reconcile later.

    A root's own ``skills/<name>`` WINS. A workspace holding a local copy of a
    shared skill has said something by doing that, and replacing it with the
    shared one would discard the statement. Same precedence rule packaged stock
    skills already follow.

    Returns ``(linked, pruned)``. Pruning is limited to broken links that point
    into the shared directory, so a link the user made by hand is left alone —
    the same conservative rule as ``_rebuild_custom_skill_links``.
    """
    root = Path(workspace)
    shared = Path(shared_root)
    claude_skills = root / ".claude" / "skills"
    claude_skills.mkdir(parents=True, exist_ok=True)
    own = root / "skills"
    marker = f"/{shared.name}/"

    linked = 0
    live: set[str] = set()
    if shared.is_dir():
        for entry in sorted(shared.iterdir(), key=lambda item: item.name):
            if not entry.is_dir() or entry.name.startswith("."):
                continue
            skill_md = entry / "SKILL.md"
            if not skill_md.is_file() or skill_md.stat().st_size == 0:
                continue
            if (own / entry.name / "SKILL.md").is_file():
                continue  # the root's own copy wins
            live.add(entry.name)
            _ensure_symlink(entry, claude_skills / entry.name, relative_to=claude_skills)
            linked += 1

    pruned = 0
    for target in _iter_entries(claude_skills):
        if target.name in live or not target.is_symlink() or target.exists():
            continue
        try:
            current = os.readlink(target)
        except OSError:
            continue
        if marker not in current:
            continue
        target.unlink(missing_ok=True)
        pruned += 1
    return linked, pruned


def _stock_agent_marker(agent_path: Path) -> Path:
    return agent_path.with_name(agent_path.name + STOCK_AGENT_MARKER_SUFFIX)


def _is_managed_stock_agent(agent_path: Path) -> bool:
    return _stock_agent_marker(agent_path).is_file()


def _mark_stock_agent(agent_path: Path) -> None:
    _stock_agent_marker(agent_path).touch()


def _unmark_stock_agent(agent_path: Path) -> None:
    _stock_agent_marker(agent_path).unlink(missing_ok=True)


def _install_stock_agents(workspace: Path) -> tuple[int, int]:
    """Copy packaged ``ciao.stock/agents`` into ``.claude/agents``.

    A workspace ``subagents/<name>.md`` always wins over the packaged agent of
    the same name. Copies carry a sibling ``*.ciao-stock-agent`` marker so they
    are refreshed on every sync and pruned once they disappear from the package
    (or become shadowed by a workspace subagent).
    """
    from importlib import resources

    agents_dir = workspace / ".claude" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    custom_dir = workspace / "subagents"

    try:
        stock_agents = resources.files("ciao.stock").joinpath("agents")
        stock_files = sorted(
            (entry for entry in stock_agents.iterdir() if entry.name.endswith(".md")),
            key=lambda item: item.name,
        )
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        stock_files = []

    installed = 0
    live: set[str] = set()
    for stock_entry in stock_files:
        name = stock_entry.name
        if (custom_dir / name).is_file():
            continue  # workspace subagent shadows the packaged agent
        target = agents_dir / name
        if target.is_symlink():
            continue  # user-managed link, leave it alone
        with resources.as_file(stock_entry) as stock_path:
            shutil.copy2(stock_path, target)
        _mark_stock_agent(target)
        live.add(name)
        installed += 1

    pruned = 0
    for existing in _iter_entries(agents_dir):
        if not existing.is_file() or existing.name.endswith(STOCK_AGENT_MARKER_SUFFIX):
            continue
        if not existing.name.endswith(".md") or existing.is_symlink():
            continue
        if existing.name in live:
            continue
        if _is_managed_stock_agent(existing):
            _remove_path(existing)
            _unmark_stock_agent(existing)
            pruned += 1
            continue
        if (
            existing.stem in LEGACY_REMOVED_STOCK_AGENTS
            and not (custom_dir / existing.name).is_file()
        ):
            _remove_path(existing)
            pruned += 1

    for marker in agents_dir.glob(f"*{STOCK_AGENT_MARKER_SUFFIX}"):
        agent_path = marker.with_name(marker.name[: -len(STOCK_AGENT_MARKER_SUFFIX)])
        if agent_path.name not in live and not agent_path.exists():
            marker.unlink(missing_ok=True)

    return installed, pruned


def _seed_stock_commands(workspace: Path) -> int:
    """Ensure packaged commands live in canonical ``commands/``.

    Fresh installs seed from ``ciao.stock/commands``. Older workspaces that
    still have stock copies only under ``.claude/commands/`` are migrated
    into ``commands/`` so they become editable and covered by weekly-review
    hygiene checks.
    """
    from importlib import resources

    commands_dir = workspace / "commands"
    commands_dir.mkdir(parents=True, exist_ok=True)
    claude_commands = workspace / ".claude" / "commands"

    try:
        stock_commands = resources.files("ciao.stock").joinpath("commands")
        stock_files = sorted(
            (entry for entry in stock_commands.iterdir() if entry.name.endswith(".md")),
            key=lambda item: item.name,
        )
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        return 0

    seeded = 0
    for stock_entry in stock_files:
        canonical = commands_dir / stock_entry.name
        if canonical.exists():
            continue
        legacy = claude_commands / stock_entry.name
        with resources.as_file(stock_entry) as stock_path:
            stock_text = stock_path.read_text(encoding="utf-8")
            if legacy.is_file() and not legacy.is_symlink():
                # Legacy stock installs lived only under .claude/commands/ and
                # were not editable in Settings — seed the packaged revision.
                canonical.write_text(stock_text, encoding="utf-8")
            else:
                shutil.copy2(stock_path, canonical)
        seeded += 1
    return seeded


def _mirror_dir_symlinks(
    source_dir: Path,
    dest_dir: Path,
    *,
    glob_pattern: str = "*",
    prune_regular: bool,
) -> tuple[int, int]:
    dest_dir.mkdir(parents=True, exist_ok=True)
    linked = 0
    live: set[str] = set()
    if source_dir.is_dir():
        for entry in sorted(source_dir.glob(glob_pattern), key=lambda item: item.name):
            if not entry.exists():
                if entry.is_symlink():
                    print(
                        f"WARN: skipping dangling symlink {entry} -> {os.readlink(entry)}",
                        file=sys.stderr,
                    )
                continue
            live.add(entry.name)
            _ensure_symlink(entry, dest_dir / entry.name)
            linked += 1

    pruned = 0
    for entry in _iter_entries(dest_dir):
        if entry.name in live:
            continue
        if not prune_regular and not entry.is_symlink():
            continue
        _remove_path(entry)
        pruned += 1
    return linked, pruned


def _frontmatter_and_body(text: str) -> tuple[dict[str, str], str]:
    from ciao.web.commands import _FRONTMATTER_RE, _parse_frontmatter

    return _parse_frontmatter(text), _FRONTMATTER_RE.sub("", text, count=1).strip()


def _without_managed_codex_config(text: str) -> tuple[str, bool]:
    """Remove Ciaobot's prior agent-registration block from TOML text."""
    start = text.find(CODEX_CONFIG_BEGIN)
    if start < 0:
        return text, False
    end = text.find(CODEX_CONFIG_END, start)
    if end < 0:
        # A partial marker may be user-edited or truncated. Refuse to guess.
        return text, True
    end += len(CODEX_CONFIG_END)
    if end < len(text) and text[end] == "\n":
        end += 1
    return (text[:start].rstrip() + "\n" + text[end:].lstrip()).strip() + "\n", False


def _without_managed_codex_mcp_config(text: str) -> tuple[str, bool]:
    """Remove Ciaobot's prior project-MCP block from TOML text."""
    start = text.find(CODEX_MCP_CONFIG_BEGIN)
    if start < 0:
        return text, False
    end = text.find(CODEX_MCP_CONFIG_END, start)
    if end < 0:
        # A partial marker may be user-edited or truncated. Refuse to guess.
        return text, True
    end += len(CODEX_MCP_CONFIG_END)
    if end < len(text) and text[end] == "\n":
        end += 1
    return (text[:start].rstrip() + "\n" + text[end:].lstrip()).strip() + "\n", False


def _cleanup_legacy_codex_projections(workspace: Path) -> int:
    """Remove only artifacts Ciaobot can prove it generated for Codex.

    Codex is no longer a runtime provider, but upgrades must not delete a
    user's own ``.codex`` configuration or skills. Every removable artifact
    therefore carries one of the old Ciaobot markers; unmarked files are left
    untouched.
    """
    pruned = 0
    wrapper_root = workspace / ".agents" / "skills"
    for entry in _iter_entries(wrapper_root):
        if entry.is_dir() and (entry / CODEX_WRAPPER_MARKER).is_file():
            _remove_path(entry)
            pruned += 1

    agent_root = workspace / ".codex" / "agents"
    for entry in _iter_entries(agent_root):
        if not entry.is_file() or entry.suffix != ".toml":
            continue
        try:
            managed = entry.read_text(encoding="utf-8").startswith(CODEX_AGENT_MARKER)
        except OSError:
            continue
        if managed:
            _remove_path(entry)
            pruned += 1

    config_path = workspace / ".codex" / "config.toml"
    try:
        original = config_path.read_text(encoding="utf-8")
    except (FileNotFoundError, OSError):
        original = ""
    if original:
        without_agents, partial_agents = _without_managed_codex_config(original)
        without_mcps, partial_mcps = _without_managed_codex_mcp_config(without_agents)
        if not partial_agents and not partial_mcps and without_mcps != original:
            config_path.write_text(without_mcps, encoding="utf-8")
            pruned += 1
    return pruned


def _env_var_name(value: object) -> str:
    """The variable name behind a `${NAME}` reference, else "".

    A literal value yields "" so callers drop it rather than copy a credential
    into a tracked config file.
    """
    raw = str(value or "").strip()
    match = re.fullmatch(r"\$\{([A-Za-z_][A-Za-z0-9_]*)\}", raw)
    return match.group(1) if match else ""


def _opencode_env_placeholder(value: object) -> str:
    """Return an opencode `{env:NAME}` reference, never a literal credential.

    opencode does not understand `${NAME}`. Its config interpolation is
    `{env:VAR}` (plus `{file:path}`), and anything else is passed through
    verbatim — a projected `${NOTION_TOKEN}` reached the Notion MCP server as
    the literal bearer token and every call came back 401. The remote branch of
    `_opencode_mcp_entry` already emitted the right shape; only local servers,
    which carry credentials in `environment`, were wrong.
    """
    name = _env_var_name(value)
    return f"{{env:{name}}}" if name else ""


def _bearer_env_name(headers: object) -> str:
    if not isinstance(headers, dict):
        return ""
    authorization = str(headers.get("Authorization") or headers.get("authorization") or "")
    match = re.fullmatch(r"Bearer\s+\$\{([A-Za-z_][A-Za-z0-9_]*)\}", authorization.strip())
    return match.group(1) if match else ""


def _opencode_generated(path: Path) -> bool:
    """Whether a generated file is Ciaobot's to rewrite or prune."""
    try:
        return OPENCODE_GENERATED_MARKER in path.read_text(encoding="utf-8")
    except OSError:
        return False


def _write_opencode_projection(target: Path, frontmatter: list[str], body: str) -> bool:
    """Write a marked Markdown projection, leaving user-authored files alone."""
    if target.exists() and not _opencode_generated(target):
        return False
    content = (
        "---\n" + "\n".join(frontmatter) + "\n---\n\n"
        + OPENCODE_GENERATED_MARKER + "\n\n"
        + body.strip() + "\n"
    )
    try:
        if target.exists() and target.read_text(encoding="utf-8") == content:
            return True
        target.write_text(content, encoding="utf-8")
    except OSError:
        return False
    return True


def _prune_opencode_dir(target_root: Path, live: set[str]) -> int:
    """Remove generated files no longer backed by a canonical source."""
    pruned = 0
    for entry in _iter_entries(target_root):
        if entry.name in live or not entry.is_file():
            continue
        if not _opencode_generated(entry):
            continue
        _remove_path(entry)
        pruned += 1
    return pruned


def _install_opencode_agents(workspace: Path) -> tuple[int, int]:
    """Compile canonical Ciaobot roles into opencode subagent definitions.

    opencode's agent format is Markdown with YAML frontmatter, so the canonical
    `subagents/<name>.md` files need only a `mode: subagent` line added.
    `tools` and `model` are deliberately omitted: omission inherits the
    parent's, which is safer than translating Claude tool names.
    """
    target_root = workspace / ".opencode" / "agents"
    target_root.mkdir(parents=True, exist_ok=True)
    live: set[str] = set()
    installed = 0
    for source in _canonical_agent_sources(workspace):
        name = source.stem
        if not _AGENT_NAME_RE.fullmatch(name):
            continue
        try:
            frontmatter, body = _frontmatter_and_body(source.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not body.strip():
            continue
        description = frontmatter.get("description", "").strip() or f"Ciaobot {name} role"
        target = target_root / f"{name}.md"
        if _write_opencode_projection(
            target,
            [f"description: {json.dumps(description, ensure_ascii=False)}", "mode: subagent"],
            body,
        ):
            live.add(target.name)
            installed += 1
    return installed, _prune_opencode_dir(target_root, live)


def _install_opencode_commands(workspace: Path) -> tuple[int, int]:
    """Project canonical Ciaobot commands into opencode's command directory.

    opencode uses the same Markdown-plus-`$ARGUMENTS` shape as the canonical
    files, so the body passes through untouched.
    """
    target_root = workspace / ".opencode" / "commands"
    target_root.mkdir(parents=True, exist_ok=True)
    live: set[str] = set()
    installed = 0
    for source in _iter_entries(workspace / ".claude" / "commands"):
        if not source.is_file() or source.suffix != ".md":
            continue
        try:
            frontmatter, body = _frontmatter_and_body(source.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not body.strip():
            continue
        description = (
            frontmatter.get("description", "").strip() or f"Ciaobot /{source.stem} command"
        )
        target = target_root / f"{source.stem}.md"
        if _write_opencode_projection(
            target,
            [f"description: {json.dumps(description, ensure_ascii=False)}"],
            body,
        ):
            live.add(target.name)
            installed += 1
    return installed, _prune_opencode_dir(target_root, live)


def _install_opencode_mcps(workspace: Path) -> tuple[int, int]:
    """Project `.mcp.json` into `opencode.json`, preserving user-owned entries.

    JSON has no comment syntax, so a marker-fence approach does not transfer.
    Ciaobot instead records the server
    names it owns in `.opencode/.ciao-managed-mcps.json` and prunes only those.
    A name the user has defined themselves is never touched.
    """
    source = workspace / ".mcp.json"
    config_path = workspace / "opencode.json"
    sidecar = workspace / ".opencode" / OPENCODE_MANAGED_MCPS_FILE

    try:
        previous = set(json.loads(sidecar.read_text(encoding="utf-8")))
    except (OSError, json.JSONDecodeError, TypeError):
        previous = set()

    desired: dict[str, dict] = {}
    if source.is_file():
        try:
            data = json.loads(source.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError, TypeError):
            print(
                f"WARN: invalid MCP config at {source}; opencode MCP sync skipped",
                file=sys.stderr,
            )
            return 0, 0
        servers: object = {}
        if isinstance(data, dict):
            servers = data.get("mcpServers") or data.get("mcp_servers") or {}
        if isinstance(servers, dict):
            for raw_name, meta in servers.items():
                name = str(raw_name).strip()
                if not name or name in OPENCODE_MCP_EXCLUDES or not isinstance(meta, dict):
                    continue
                entry = _opencode_mcp_entry(meta)
                if entry:
                    desired[name] = entry

    try:
        config = json.loads(config_path.read_text(encoding="utf-8"))
    except FileNotFoundError:
        config = {}
    except (OSError, json.JSONDecodeError, TypeError):
        print(
            f"WARN: invalid {config_path}; opencode MCP sync skipped",
            file=sys.stderr,
        )
        return 0, 0
    if not isinstance(config, dict):
        return 0, 0

    existing = config.get("mcp")
    servers_out = dict(existing) if isinstance(existing, dict) else {}
    # Never clobber a server the user declared; only previously-managed names
    # are ours to rewrite or remove.
    installed = 0
    managed: set[str] = set()
    for name, entry in desired.items():
        if name in servers_out and name not in previous:
            continue
        servers_out[name] = entry
        # Only what we actually wrote goes in the sidecar. Recording every
        # *desired* name would claim ownership of the user's colliding entry,
        # and the very next sync would then overwrite it (and prune it once
        # `.mcp.json` dropped the name) — the guard above would last one run.
        managed.add(name)
        installed += 1
    pruned = 0
    for name in previous - set(desired):
        if servers_out.pop(name, None) is not None:
            pruned += 1

    config.setdefault("$schema", "https://opencode.ai/config.json")
    if servers_out:
        config["mcp"] = servers_out
    else:
        config.pop("mcp", None)

    rendered = json.dumps(config, indent=2, ensure_ascii=False) + "\n"
    try:
        if not config_path.exists() or config_path.read_text(encoding="utf-8") != rendered:
            config_path.write_text(rendered, encoding="utf-8")
        sidecar.parent.mkdir(parents=True, exist_ok=True)
        sidecar.write_text(
            json.dumps(sorted(managed), indent=2) + "\n", encoding="utf-8"
        )
    except OSError:
        return 0, 0
    return installed, pruned


def _opencode_mcp_entry(meta: dict) -> dict | None:
    """One `.mcp.json` server in opencode's `mcp` object shape.

    Credentials stay environment references: a literal value is dropped rather
    than copied into a tracked config file.
    """
    url = str(meta.get("url") or "").strip()
    if url:
        entry: dict = {"type": "remote", "url": url, "enabled": True}
        bearer_env = str(meta.get("bearer_token_env_var") or "").strip()
        bearer_env = bearer_env or _bearer_env_name(meta.get("headers"))
        if bearer_env:
            entry["headers"] = {"Authorization": f"Bearer {{env:{bearer_env}}}"}
        return entry
    command = str(meta.get("command") or "").strip()
    if not command:
        return None
    args = meta.get("args")
    args = [str(arg) for arg in args] if isinstance(args, list) else []
    entry = {"type": "local", "command": [command, *args], "enabled": True}
    env = meta.get("env")
    if isinstance(env, dict):
        environment = {
            str(key): _opencode_env_placeholder(value)
            for key, value in sorted(env.items(), key=lambda item: str(item[0]))
            if _opencode_env_placeholder(value)
        }
        if environment:
            entry["environment"] = environment
    return entry


def _canonical_agent_sources(workspace: Path) -> list[Path]:
    """Return canonical and packaged agent projections, excluding user-only Claude files."""
    result: list[Path] = []
    for source in _iter_entries(workspace / ".claude" / "agents"):
        if not source.is_file() or source.suffix != ".md":
            continue
        canonical = False
        if source.is_symlink():
            try:
                source.resolve().relative_to((workspace / "subagents").resolve())
                canonical = True
            except (OSError, ValueError):
                pass
        if canonical or _is_managed_stock_agent(source):
            result.append(source)
    return result


def _ensure_linked_workspace_guides(workspace: Path) -> None:
    """Expose one workspace guide through both CLI-native filenames.

    ``CLAUDE.md`` is the canonical editable file and ``AGENTS.md`` is a
    relative symlink to it. Existing user-authored AGENTS.md files (including
    custom symlinks) are preserved; only a missing file or Ciaobot's packaged
    stock copy is linked.
    """
    claude_guide = workspace / "CLAUDE.md"
    agents_guide = workspace / "AGENTS.md"
    try:
        from importlib import resources

        stock_workspace = resources.files("ciao.stock").joinpath("workspace")
        stock_agents = stock_workspace.joinpath("AGENTS.md")
        stock_claude = stock_workspace.joinpath("CLAUDE.md")

        if agents_guide.is_symlink():
            return
        if agents_guide.exists():
            if agents_guide.read_bytes() != stock_agents.read_bytes():
                return
            agents_guide.unlink()

        if not claude_guide.exists():
            with resources.as_file(stock_claude) as source:
                shutil.copy2(source, claude_guide)
        agents_guide.symlink_to(claude_guide.name)
    except (ModuleNotFoundError, FileNotFoundError, OSError):
        return


def _resolve_vault_root(workspace: Path) -> Path:
    """Vault root for a workspace checkout, honouring the env override.

    Mirrors ``ciao.cli``'s resolution rather than building a ``CiaoConfig``: this
    runs inside skill sync, which must not fail because the wider config is
    mid-setup.
    """
    raw = os.environ.get("CIAO_VAULT_ROOT", "").strip() or "memory-vault"
    root = Path(raw).expanduser()
    return root if root.is_absolute() else workspace / root


def _resolve_runtime_root(workspace: Path) -> Path:
    raw = os.environ.get("CIAO_RUNTIME_ROOT", "").strip() or ".runtime"
    root = Path(raw).expanduser()
    return root if root.is_absolute() else workspace / root


def sync_workspace_skills(
    workspace: Path | str,
    *,
    refresh_upstream: bool = True,
    runner=subprocess.run,
) -> SyncSkillsResult:
    root = Path(workspace).expanduser().resolve()
    _ensure_linked_workspace_guides(root)
    try:
        from ciao import job_runs
        from ciao.memory_tool import default_memory_dir, ensure_regions, migrate_legacy_files

        guide = root / "CLAUDE.md"
        # The legacy fold-in can only ever succeed once, so only pay for it
        # (and record a job run) while the old files are actually there.
        legacy_dir = default_memory_dir()
        if any((legacy_dir / name).is_file() for name in ("memory.md", "user.md")):
            with job_runs.track_sync(
                "memory_migration", "Legacy memory migration"
            ) as run:
                # migrate_legacy_files ensures the regions itself.
                migration = migrate_legacy_files(guide)
                run.extra["migrated"] = migration.get("migrated", [])
                if not migration.get("migrated"):
                    run.skip("no legacy memory files to migrate")
        else:
            ensure_regions(guide)
    except Exception:  # noqa: BLE001 — never block skill sync on memory regions
        logger.exception(
            "memory region ensure/migrate failed for %s; continuing skill sync",
            root,
        )

    try:
        from ciao import job_runs
        from ciao.vault_migration import migrate_if_needed, read_receipt

        vault_root = _resolve_vault_root(root)
        runtime_root = _resolve_runtime_root(root)
        # Receipt-gated so an existing install pays for the vault scan once, not
        # on every boot. `vault-lint` starts reporting non-canonical types on
        # upgrade, so without this an existing vault would hand the user a
        # permanently failing `os-audit`.
        if read_receipt(runtime_root) is None:
            with job_runs.track_sync(
                "vault_vocabulary_migration", "Vault vocabulary migration"
            ) as run:
                summary = migrate_if_needed(vault_root, runtime_root)
                renamed = summary.get("renamed") or []
                unresolved = summary.get("unresolved") or {}
                run.extra["renamed"] = len(renamed)
                run.extra["unresolved"] = sorted(unresolved)
                if summary.get("skipped"):
                    run.skip(str(summary["skipped"]))
                elif not renamed and not unresolved:
                    run.skip("vault types already canonical")
    except Exception:  # noqa: BLE001 — never block skill sync on the vault
        logger.exception(
            "vault vocabulary migration failed for %s; continuing skill sync",
            root,
        )

    upstream_updated = 0
    upstream_pruned = 0
    if refresh_upstream:
        upstream_updated, upstream_pruned = _refresh_upstream_skills(root, runner=runner)

    legacy_codex_pruned = _cleanup_legacy_codex_projections(root)
    stock_installed, stock_pruned = _install_stock_skills(root)
    custom_installed, custom_pruned = _rebuild_custom_skill_links(root)
    stock_agents_installed, stock_agents_pruned = _install_stock_agents(root)
    print(
        f"Skills: {stock_installed} stock skills installed ({stock_pruned} stale pruned), "
        f"{custom_installed} custom-skill symlinks rebuilt, "
        f"{custom_pruned} orphaned pruned."
    )
    if stock_agents_installed or stock_agents_pruned:
        print(
            f"Skills: {stock_agents_installed} stock agent(s) installed "
            f"({stock_agents_pruned} stale pruned)."
        )
    agents_installed, agents_pruned = _mirror_dir_symlinks(
        root / "subagents",
        root / ".claude" / "agents",
        glob_pattern="*.md",
        prune_regular=False,
    )
    stock_commands_seeded = _seed_stock_commands(root)
    if stock_commands_seeded:
        print(f"Skills: {stock_commands_seeded} stock command(s) seeded into commands/.")
    commands_installed, commands_pruned = _mirror_dir_symlinks(
        root / "commands",
        root / ".claude" / "commands",
        glob_pattern="*.md",
        prune_regular=False,
    )
    # opencode reads .claude/skills, .agents/skills, AGENTS.md and CLAUDE.md
    # natively, so only commands, subagents, and MCP servers are projected.
    opencode_agents_installed, opencode_agents_pruned = _install_opencode_agents(root)
    opencode_commands_installed, opencode_commands_pruned = _install_opencode_commands(root)
    opencode_mcps_installed, opencode_mcps_pruned = _install_opencode_mcps(root)
    print(
        f"Skills: {agents_installed} custom-agent symlinks rebuilt, "
        f"{commands_installed} command links rebuilt; "
        f"{agents_pruned + commands_pruned} orphaned pruned."
    )
    if legacy_codex_pruned:
        print(f"Legacy Codex projections removed: {legacy_codex_pruned} marked artifact(s).")
    print(
        f"opencode: {opencode_agents_installed} subagent(s) and "
        f"{opencode_commands_installed} command(s) projected, "
        f"{opencode_mcps_installed} project MCP server(s) synced; "
        f"{opencode_agents_pruned + opencode_commands_pruned + opencode_mcps_pruned} "
        "stale pruned. Skills and instructions are read natively."
    )

    return SyncSkillsResult(
        custom_installed=custom_installed,
        custom_pruned=custom_pruned,
        upstream_updated=upstream_updated,
        upstream_pruned=upstream_pruned,
        agents_installed=agents_installed,
        agents_pruned=agents_pruned,
        commands_installed=commands_installed,
        commands_pruned=commands_pruned,
        stock_installed=stock_installed,
        stock_pruned=stock_pruned,
        stock_agents_installed=stock_agents_installed,
        stock_agents_pruned=stock_agents_pruned,
        legacy_codex_pruned=legacy_codex_pruned,
        opencode_agents_installed=opencode_agents_installed,
        opencode_agents_pruned=opencode_agents_pruned,
        opencode_commands_installed=opencode_commands_installed,
        opencode_commands_pruned=opencode_commands_pruned,
        opencode_mcps_installed=opencode_mcps_installed,
        opencode_mcps_pruned=opencode_mcps_pruned,
    )


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace",
        type=Path,
        default=Path("."),
        help="Workspace root. Defaults to current directory.",
    )
    parser.add_argument(
        "--skip-upstream",
        action="store_true",
        help="Skip skills-lock.json remote refresh and only mirror local catalogs.",
    )
    parser.add_argument("--verbose", action="store_true", help="Accepted for script compatibility.")
    args = parser.parse_args(list(argv) if argv is not None else None)
    sync_workspace_skills(
        args.workspace,
        refresh_upstream=not args.skip_upstream,
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
